### ISSUE TITLE
Redirect to IP address of host instead of 'localhost'?

### ISSUE THREAD

**Issue by akashbedu** [spurin/diveintoansible-lab#102]
Hello,

For my setup, I have a Ubuntu server VM on which I have installed docker and docker-compose. Now the port mappings are there, and I am able to access the applications from my main OS with the IP address, however the individual application links (like ansible terminal) re-direct to 'localhost:<port>' - is there any way to configure it in a way the applications re-direct to <host-ip-address>:<port> instead of localhost?

Thanks :)

**Comment by spurin** [comment]
Hi @akashbedu

Yes, in your case you can edit the docker-compose.yaml file, in the portal, add an environmental as follows:

- LOCALHOST_OVERRIDE=1.2.3.4

With your IP address, restart the lab and you should be good

**Comment by akashbedu** [comment]
@spurin - Works like a charm! Thanks a lot for the quick help! 👍
