### ISSUE TITLE
KDE Crashes when deploying compose

### ISSUE THREAD

**Issue by n0ct1s-k8sh** [spurin/diveintoansible-lab#106]
Hi James, first of all thank you for all your effort and work to make us learn the best we can!

When I run `docker-compose up -d` in the terminal to run all the containers, my KDE desktop crashes and forces me to relogin. The containers seems to be working good but the problem is the KDE crash.

But, if I remove all the `privileged` flags in the docker-compose file, KDE won't crash.

Thank you!

**Comment by spurin** [comment]
Thanks for sharing this by the way, just going back through and closing past issues
