### ISSUE TITLE
You have reached your pull rate limit.

### ISSUE THREAD

**Issue by shorn89** [spurin/diveintoansible-lab#108]
I am on the Installing Ansible Lab section of the Dive In, and I keep getting the error "Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"

This is after I attempt to "docker-compose up"

Any ideas on what I am doing wrong?  Are we supposed to pay for a premium docker membership?

**Comment by shorn89** [comment]
![Error Pull Rate](https://user-images.githubusercontent.com/47042991/208491255-0344ca6e-c998-4042-b6c5-b132d16cd209.PNG)

**Comment by spurin** [comment]
Hi @shorn89,

Checking this right away, you shouldn't be having this issue.  I pay for a repository so that you don't hit this limit.

I'll come back to you on it shortly.

Thanks


James Spurin

**Comment by spurin** [comment]
Hey @shorn89,

I just spoke with the team at Docker (the nice thing about being a Captain, was able to get a quick answer).  I've checked on this and it's not my side and mistakenly, my Pro subscription has nothing to do with this.

It's going to be on your side in some way but either way, we can work around it.  To give you context.

Pull limits with Docker work in two ways, if the request to pull an image is unauthenticated, the rate limit is applied to the puller's IP address (as that is the only thing that can be used).  If however, the request is authenticated, the rate limit is applied to the authenticated user and the limit is then applied on an individual basis.

Could it be that you're on a shared IP address, like that of your company/work?  If so this might explain it.

Either way, the way to resolve this in the best way will be for you creating a free Docker Hub account, then doing a ```docker login```

Once you're signed in, you wont be impacted by the limit which is currently being applied to your IP address.

Kind Regards

James Spurin

**Comment by shorn89** [comment]
Making an account, and signing in seems to have worked!  

For clarity, I am currently on a work IP address, so that would explain why the limit was reached.

Thanks for the quick response!
