### ISSUE TITLE
Link "Email: Click to Reveal Email" is broken

### ISSUE THREAD

**Issue by conloos** [spurin/diveintoansible-lab#11]
Hi James, 

the link to your email address / email contact on your website DiveInto.com is incorrect.

Greetings Frank

**Comment by spurin** [comment]
Thanks Frank, appreciate you letting me know this.  I’ll take a look.

If you wanted to drop me an email by the way, you can get me on firstname@surname.com 👍

**Comment by spurin** [comment]
Hi Frank (@conloos), I tried the link and I think the service that I'm using may be sensitive to OS/Browser etc.  What was you viewing it on?

**Comment by spurin** [comment]
@conloos closing this, think it may be browser related.  Thanks for the heads up.  I will also look at alternatives just to make sure this is covered off.
