### ISSUE TITLE
Ansible Playbooks Deep Dive Register and When -  Rev 5

### ISSUE THREAD

**Issue by marent10** [spurin/diveintoansible-lab#111]
in the register_playbook the ansible_distribution_major_version for ubuntu needs to be updated to 22.

**Comment by spurin** [comment]
Thank you @marent10 

If you wish, you can raise a pull request if you're interested in being tagged as a contributor on the repository.

No problems though if you're busy, I can pick this up also.

Appreciate you raising this.

- James Spurin

**Comment by marent10** [comment]
Hey, I don't have time to update it today, I'm fine with you picking it up.

Thanks,
