### ISSUE TITLE
Permission problem 

### ISSUE THREAD

**Issue by anishbista60** [spurin/diveintoansible-lab#113]
`/usr/bin/ssh-copy-id: INFO: Source of key(s) to be installed: "/home/ansible/.ssh/id_rsa.pub"
chmod: changing permissions of '/home/ansible/.ssh/ssh-copy-id.4jydj60Z8a': Operation not permitted
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys`

**Comment by spurin** [comment]
Hi @anishbista60 

Thanks for reaching out.  Could you please let me know more about your environment setup and what OS/platform you are running on?  

For some reason you're getting permission errors on your mounted volumes.  This will be something related to your setup.

Let me know as much detail as possible and we'll work this out.

Many Thanks


James Spurin
