### ISSUE TITLE
Support Windows clients in lab

### ISSUE THREAD

**Issue by Axell87** [spurin/diveintoansible-lab#114]
Hi there!!! Some Idea.
Very often you have to use Ansible for the Windows operating system. So, it would be great if we came up with windows support for the course.
For example 1 or 2 lightweight windows hosts (may be 7 or 10). To practice with Ansible to automate on windows!
I know windows hosts is too large for containers and so on... but still.

**Comment by spurin** [comment]
Thanks for your feedback @Axell87 - Seeing how this can be incorporated
