### ISSUE TITLE
Unable to install sshpass

### ISSUE THREAD

**Issue by amitasia1** [spurin/diveintoansible-lab#116]
SSH install failed from sudo apt update & sudo apt install sshpass

To fix the problem try
$ wget http://sourceforge.net/projects/sshpass/files/latest/download -O sshpass.tar.gz
$ tar -xvf sshpass.tar.gz
$ cd sshpass-1.06
$ ./configure
# sudo make install

**Comment by spurin** [comment]
Thanks for raising this @amitasia1 - haven't had any reports so possibly this was a one off, closing this for now but will revisit if needs be. Again, thank you
