### ISSUE TITLE
Words dont appear after writing

### ISSUE THREAD

**Issue by Sajiyah-Salat** [spurin/diveintoansible-lab#117]
Hello James, I am following your ansible course and I am on plybook video. Till now everythong was working well. but now when I type words appear after a minute. I cant see results or commands that have been typed. This is really a frustrating issue currently. What should I do? I have remove the lab installed it again. Still the same things happen. Please help. 
![Screenshot from 2023-10-18 16-14-24](https://github.com/spurin/diveintoansible-lab/assets/109643863/6b7429c7-f72a-4f3c-94dd-dc7af36faeea)

**Comment by spurin** [comment]
I suspect that it may be something with the xterm.js library that is used to render the terminal.  Can we try a quick experiment pls.

Log into one of the ubuntu nodes as root/password

And then paste the following -

```
(cd /tmp; wget https://github.com/tsl0922/ttyd/releases/download/1.7.4/ttyd.x86_64; wget https://github.com/tsl0922/ttyd/releases/download/1.7.4/ttyd.aarch64; chmod 755 ttyd.*; mv ttyd.* /bin/)
```

Then please refresh that page and log in again as ansible.  We'll see then if it's any better.

**Comment by Sajiyah-Salat** [comment]
![Screenshot from 2023-10-18 21-01-30](https://github.com/spurin/diveintoansible-lab/assets/109643863/6870f667-ee93-4b1e-a472-9eac52470d79)

when there is a question at the end of the script I tried using enter or  yes or y. none of them worked and permission denied. What should I do?

**Comment by spurin** [comment]
You'll need to be logged in as root, do the initial login with the username of root and then password as the password, then paste the command.

**Comment by Sajiyah-Salat** [comment]
I logged in as root, and pasted the command runs well. But still the same issue or I would its been worse as its crashing now as well. 
I am on ubuntu 22 and the web browser is chrome
I have 8gb of ram as well. Still its not working why?

**Comment by spurin** [comment]
Thanks @Sajiyah-Salat - appreciate your time troubleshooting this.  For anyone else following the thread, a recent chrome update has identified some issues with the xterm.js rendering used in the lab.  At present you'll need to use a different browser to work around.  I'm going to update the lab with a newer version to get around this.

**Comment by spurin** [comment]
Closed the issue by mistake, will close once the new lab is released

**Comment by spurin** [comment]
Hi @Sajiyah-Salat 

I'm pleased to let you know that an updated lab has been rolled out. If you issue the following commands, this should fix the issues you were encountering. Again, appreciate your time in troubleshooting this.

Please check and confirm all is as expected from Chrome on your side, in the diveintoansible-lab directory -

```
docker compose down
docker compose rm
docker compose pull
docker compose up
```

Best Regards


James

**Comment by Sajiyah-Salat** [comment]
Yes, will do that soon! Thank you for upgrading
