### ISSUE TITLE
README Windows config needs clarification

### ISSUE THREAD

**Issue by vgrazi** [spurin/diveintoansible-lab#12]
In the below, there are a couple of items that can use some clarification.
1. What does n.b. stand for??
2. The windows CONFIG and ANSIBLE_HOME values are confusing. What is /host_mnt? From the course video I understand that host_mnt is just an incantation used by Ansible, but it would be great if this could be explained in the readme, since it was mentioned to refer to the readme in case the video becomes out of date. Something like

`Note: Ansible requires these entries to be Unix style paths, beginning with /host_mnt/`

```
Windows (**n.b.** 'users' and the username (in my case this is james) are in lowercase, this is important) -
# Shared config volume
CONFIG=/**host_mnt**/c/users/james/diveintoansible-lab/config

# Shared home directories
ANSIBLE_HOME=/**host_mnt**/c/users/james/diveintoansible-lab/ansible_home
```

**Comment by spurin** [comment]
Hey Victor,

I guess the n.b. use may be more commonly used in UK than it's used elsewhere in the world :-)  It is typically used as 'note'.  It's from the latin phrase 'Nota Bene', meaning 'Note Well'.  Given that it's caused confusion I'll update this.  That being said, it is a perfect opportunity for my latin joke ....

"Don't you just love it when people switch between English and Latin ... and Vice Versa" 🤣

With regards to the host path, this is a specific with Docker Desktop on Windows.  As Docker requires a Linux environment for execution, both Docker Desktop for Mac/Windows get around this by using a Linux Subsystem variation.  It used to be Virtualbox in the background for both of them but now Windows has geared towards WSL (Windows Subsystem for Linux).

In this case /host_mnt/c is an internal reference within the Docker Desktop Windows incarnation and this is how you gain access to the local drives from the respective linux VM.

I have another plan with regards to the user guide for this and it's currently a work in progress and this relates in the same way to install environments constantly evolving.  I'm working on a user guide for the lab where individuals can follow a guided path and it will instruct accordingly, what to do and what to check.  The idea being, that this can be updated more easily without have edit/republish course content.

Hope this helps.  Closing the issue for now 👍
