### ISSUE TITLE
/diveintoansible/ directory missing on ubuntu-c

### ISSUE THREAD

**Issue by xpact2** [spurin/diveintoansible-lab#120]
/diveintoansible/ directory missing on ubuntu-c

Up to section 3: Ansible Architecture and Design  Chapter 9 in the UDEMY course everything works.

All hosts control host, ubuntu centos hosts are created. I can ssh copy keys back and forth no issues.

However I don't see anywhere the /diveintoansible directory.
![ubuntu001](https://github.com/spurin/diveintoansible-lab/assets/47746131/008bfba5-2539-42f5-b752-fd00b578792b)

**Comment by spurin** [comment]
Stale issue, is this is still a problem please let me know and we can re-open.
