### ISSUE TITLE
Receiving network timeout after logging into ubuntu-c with ansible/password

### ISSUE THREAD

**Issue by brianclaus73** [spurin/diveintoansible-lab#13]
When I attempt to log into ubuntu-c as per the lab setup, it allows me to login then gives me a timeout message.

I'm running on Windows 10 home, WSL and most recent docker desktop.
I've been using docker for other users without issues, including setting up ubuntu docker images on bridge networks on my laptop.

Edit: I am able to access the localhost:1000 web-page.

I haven't made any changes to any files except for the .env file as per the instructions in the setup.

Login:
![image](https://user-images.githubusercontent.com/54034343/105571427-aaf53a00-5d8a-11eb-96cb-e8436e06bf1b.png)

here is the docker-compose startup
![image](https://user-images.githubusercontent.com/54034343/105571435-bd6f7380-5d8a-11eb-8406-9be60f6dd8e9.png)

Here is my .env file
![image](https://user-images.githubusercontent.com/54034343/105571467-f576b680-5d8a-11eb-96aa-80fa25dba458.png)

**Comment by brianclaus73** [comment]
I also tried move this to /hostmnt/c/users/brian/diveintoansible-lab/<config>/<ansible> with the same result as above. (In case it was some strange problem with 'IdeaProjects'

**Comment by spurin** [comment]
Hi Brian,

I think I may know what is going wrong here but just need to confirm some small bits, can you please get me the exact Windows version and build (start, run, winver), also, can you confirm the version of wsl (at a powershell prompt, run wsl -l -v) if you see a version number it's wsl2, if not it's wsl1.

Doesn't matter which version, we'll work on getting it working regardless, just need to know what we're working with.

Thanks


James Spurin

**Comment by brianclaus73** [comment]
Here is my windows version
![image](https://user-images.githubusercontent.com/54034343/105824339-2d833100-5ff9-11eb-95f6-0468577dc4bc.png)

Here is my wsl version
![image](https://user-images.githubusercontent.com/54034343/105824426-4a1f6900-5ff9-11eb-9466-77fea3a67a8d.png)

**Comment by spurin** [comment]
Hi Brian,

Just re-reading through this and apologies for the delay in getting back to you.  Do the sessions work okay when you access them through the brower?

Also, it may be worthwhile, you just ssh'ing to them rather than using docker-login, if, it's the case of you preferring not to use the web terminal for this.

In the config file are the ports specified so you for example, can just ssh localhost on the corresponding port.

**Comment by spurin** [comment]
Hi @brianclaus73 

Hope you're doing well, haven't heard back so assuming this is good.  Please re-open if there are still issues.

Thanks


James Spurin
