### ISSUE TITLE
Unable to connect to individual hosts after getting to localhost:1000

### ISSUE THREAD

**Issue by frankdin1** [spurin/diveintoansible-lab#133]
On Windows 10 these are my current configurations in the .env file
`
# sshd ports
UBUNTUC_PORT_SSHD=2221
UBUNTU1_PORT_SSHD=2222
UBUNTU2_PORT_SSHD=2223
UBUNTU3_PORT_SSHD=2224
CENTOS1_PORT_SSHD=2225
CENTOS2_PORT_SSHD=2226
CENTOS3_PORT_SSHD=2227

# ttyd (web terminal) ports
UBUNTUC_PORT_TTYD=50000
UBUNTU1_PORT_TTYD=50001
UBUNTU2_PORT_TTYD=50002
UBUNTU3_PORT_TTYD=50003
CENTOS1_PORT_TTYD=50004
CENTOS2_PORT_TTYD=50005
CENTOS3_PORT_TTYD=50006
`
With these configurations, I am able to access the home page on localhost:1000, but when I click on any of the docker images I get this error
![image](https://github.com/spurin/diveintoansible-lab/assets/50062629/3ddd8016-7276-453c-b216-56ec1fcf6651)

**Comment by spurin** [comment]
Hi @frankdin1, the overrides sadly don't relate to the ports used in the app, I wasn't really expecting students to change this. If you still need this, reach out to me on slack and we'll discuss it further.
