### ISSUE TITLE
fedora 33 even with docker.io .. 

### ISSUE THREAD

**Issue by bcookatpcsd** [spurin/diveintoansible-lab#15]
Hey there.. 

Lurker of the Udemy.. been listening to the audio here in NY, USA while shoveling snow.. 

Decided to make the labs and give it a go.. 

tl:dr; fedora 33 (can't make it work) clearlinux - of course it works.. 

portal      | 2021/02/11 02:50:18 [emerg] 1#1: host not found in upstream "ubuntu1" in /etc/nginx/conf.d/default.conf:46

 [2]# cat /proc/cmdline
BOOT_IMAGE=(hd0,gpt2)/boot/vmlinuz-5.10.13-200.fc33.x86_64 root=UUID=448267b7-614f-43d2-a0cc-72113faa7d10 ro resume=UUID=9239ee84-9014-489b-9350-393baa12ee38 rhgb quiet mitigations=off systemd.unified_cgroup_hierarchy=0

 docker version
Client: Docker Engine - Community
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:33:58 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

 hostnamectl
   Static hostname: fedora.vlan10.dns
         Icon name: computer-desktop
           Chassis: desktop
        Machine ID: c8d483188c7e4356a4d3028e1928ba27
           Boot ID: 2bfc8bd99f70413bab16ee5ef3048692
  Operating System: Fedora 33 (Thirty Three)
       CPE OS Name: cpe:/o:fedoraproject:fedora:33
            Kernel: Linux 5.10.13-200.fc33.x86_64
      Architecture: x86-64

root@fedora ~/g/diveintoansible-lab (master)# export CONFIG=/root/github/diveintoansible-lab/config
root@fedora ~/g/diveintoansible-lab (master)# export ANSIBLE_HOME=/root/github/diveintoansible-lab/ansible_home
root@fedora ~/g/diveintoansible-lab (master)# docker-compose up
Starting centos2  ... done
Starting docker   ... done
Starting centos3  ... done
Starting centos1  ... done
Starting ubuntu1  ... done
Starting ubuntu3  ... done
Starting ubuntu2  ... done
Starting ubuntu-c ... done
Starting portal   ... done
Attaching to docker, ubuntu1, ubuntu2, ubuntu3, ubuntu-c, centos3, centos1, centos2, portal
ubuntu-c exited with code 255
ubuntu3 exited with code 255
ubuntu1 exited with code 255
ubuntu2 exited with code 255
portal      | 2021/02/11 02:55:38 [emerg] 1#1: host not found in upstream "ubuntu1" in /etc/nginx/conf.d/default.conf:46
portal      | nginx: [emerg] host not found in upstream "ubuntu1" in /etc/nginx/conf.d/default.conf:46
portal exited with code 1

 [2]# mount | grep cgroup
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,size=4096k,nr_inodes=1024,mode=755,inode64)
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)

root@clear-docker ~/g/diveintoansible-lab (master)# docker-compose up
Starting ubuntu1  ... done
Starting docker   ... done
Starting ubuntu2  ... done
Starting centos3  ... done
Starting centos2  ... done
Starting centos1  ... done
Starting ubuntu-c ... done
Starting ubuntu3  ... done
Starting portal   ... done
Attaching to ubuntu2, centos1, centos3, ubuntu-c, docker, ubuntu1, ubuntu3, centos2, portal

root@clear-docker ~/g/diveintoansible-lab (master)# docker version
Client:
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.15.8
 Git commit:        afacb8b7f0d8d4f9d2a8e8736e9c993e672b41f3
 Built:             Fri Feb  5 01:15:41 2021
 OS/Arch:           linux/amd64
 Experimental:      false

 (master)# hostnamectl
   Static hostname: clear-docker
         Icon name: computer-desktop
           Chassis: desktop
        Machine ID: cdad8e76fdc84af6bee7ac8cdfd07db2
           Boot ID: a889cf58162740a98719830c80df9d65
  Operating System: Clear Linux OS
            Kernel: Linux 5.4.96-98.lts2019
      Architecture: x86-64

I do have an lts kernel in this machine.. 

So clear linux for the win.. 

Not sure why Fedora isn't doing it.. but clearlinux docker For. The. Win.

Any suggestions for Fedora? 

Thanks in advance..

**Comment by bcookatpcsd** [comment]
htop before docker-compose up

![image](https://user-images.githubusercontent.com/55087301/107598502-f6fa0880-6beb-11eb-842a-d993bc791e83.png)

Is this what they really should take?

![image](https://user-images.githubusercontent.com/55087301/107598545-18f38b00-6bec-11eb-9c28-0407969e9c64.png)

**Comment by spurin** [comment]
Hi @bcookatpcsd

Hope you're doing well, we're also enjoying the snow over here in Britain 😁

The containers are running systemd which is dependent on cgroup functionality and this has changed in Fedora 31 from cgroup v1 to cgroup v2.

This is a problem that affects other things like Kubernetes also.  The fix for this at the moment is to switch it back to cgroup v1.

This post, gives some good info - https://medium.com/nttlabs/cgroup-v2-596d035be4d7

In particular, this bit -

$ sudo dnf install -y grubby && \
  sudo grubby \
  --update-kernel=ALL \
  --args=”systemd.unified_cgroup_hierarchy=0"

After doing this, you should also sand utilisation in htop as well

**Comment by bcookatpcsd** [comment]
Hey there sir, 

Thank you for the response.. 

bcook@fedora ~> cat /proc/cmdline
BOOT_IMAGE=(hd0,gpt2)/boot/vmlinuz-5.10.13-200.fc33.x86_64 root=UUID=448267b7-614f-43d2-a0cc-72113faa7d10 ro resume=UUID=9239ee84-9014-489b-9350-393baa12ee38 rhgb quiet mitigations=off ”systemd.unified_cgroup_hierarchy=0 systemd.unified_cgroup_hierarchy=0


(not sure if you see the typo..) 

(I'm new to grubby so, I'll look into that.. )

I had to manually fix configs.. 

grubby --info=ALL will give an output of what the configs are.. (anyway)

That seemed to have been the issue.. 

 Because now:

root@fedora ~# cat /proc/cmdline
BOOT_IMAGE=(hd0,gpt2)/boot/vmlinuz-5.10.14-200.fc33.x86_64 root=UUID=448267b7-614f-43d2-a0cc-72113faa7d10 ro resume=UUID=9239ee84-9014-489b-9350-393baa12ee38 rhgb quiet mitigations=off systemd.unified_cgroup_hierarchy=0
root@fedora ~# cd github/diveintoansible-lab/
root@fedora ~/g/diveintoansible-lab (master)# ls
ansible_home/  config/  DiveIntoAnsible_Cover.png  docker-compose.yaml  README.md*
root@fedora ~/g/diveintoansible-lab (master)# docker-compose up
Recreating centos2  ... done
Recreating docker   ... done
Recreating centos1  ... done
Recreating ubuntu1  ... done
Recreating centos3  ... done
Recreating ubuntu3  ... done
Recreating ubuntu2  ... done
Recreating ubuntu-c ... done
Recreating portal   ... done
Attaching to docker, centos3, centos1, ubuntu1, ubuntu2, ubuntu-c, ubuntu3, centos2, portal

(it seems to work)

![image](https://user-images.githubusercontent.com/55087301/107655327-7837b680-6c51-11eb-8503-1ec5715258a8.png)

This is Fedora 33.. looks similar to clearlinux.. 

fwiw, when I started with docker a little over a year ago.. there were all sorts (and still are) distro issues with docker.. I only found clear linux to be a literal right out of the box working docker for everything.. 

![image](https://user-images.githubusercontent.com/55087301/107657113-d7e29180-6c52-11eb-81f8-c8c7cbf320f5.png)

This is ubuntu-c looks like systemd is using a lot of cpu.. 

https://access.redhat.com/solutions/4760541

centos machines sit at 3,4,5% (systemd)
ubuntu machines sit at 8,9,10% (systemd)

Nothing wrong on your end, and I'm not docker aware enough, but that redhat link might have some clue.. 

root@fedora ~# wc -l < /proc/1/mountinfo
52
root@fedora ~# mount | wc -l
52

No problems here, I'm good, you're great.. 

Thank you for this course.. Greatly appreciate the python explanations.. 

if you've not found 'lazydocker' (https://github.com/jesseduffield/lazydocker)

You should check it out.. 

![image](https://user-images.githubusercontent.com/55087301/107659021-b7b3d200-6c54-11eb-8f2b-2e119d260a08.png)

Centos1: 
![image](https://user-images.githubusercontent.com/55087301/107659390-1aa56900-6c55-11eb-97de-6dd4a62de609.png)


Ubuntu1:
![image](https://user-images.githubusercontent.com/55087301/107659428-23963a80-6c55-11eb-8fce-63bd814a94b2.png)

See the little cpu spikes.. 

Anyway, I'm good.. this fedora box is working.. 

Thanks for being responsive; greatly appreciated.
