### ISSUE TITLE
ERROR: Head https://registry-1.docker.io/v2/spurin/diveintoansible/manifests/ansible: unauthorized: incorrect username or password

### ISSUE THREAD

**Issue by igor-marinho** [spurin/diveintoansible-lab#19]
Issues with the docker compose up
vi .env:

`# Shared config volume
CONFIG=/Users/igor.marinho/diveintoansible-lab/config

# Shared home directories
ANSIBLE_HOME=/Users/igor.marinho/diveintoansible-lab/ansible_home
~                                                                    `

`igor.marinho@mac config % pwd
/Users/igor.marinho/diveintoansible-lab/config
igor.marinho@mac config % `

`igor.marinho@mac config % ls -ltr

-rwxrwxr-x  1 igor.marinho  staff   8 19 Mar 14:57 guest_name
-rwxrwxr-x  1 igor.marinho  staff   9 19 Mar 14:57 guest_passwd
-rwxrwxr-x  1 igor.marinho  staff  10 19 Mar 14:57 guest_shell
-rwxrwxr-x  1 igor.marinho  staff   9 19 Mar 14:57 root_passwd

igor.marinho@mac config % `

`ERROR: Head https://registry-1.docker.io/v2/spurin/diveintoansible/manifests/ansible: unauthorized: incorrect username or password`

**Comment by spurin** [comment]
Hi @igor-marinho,

I'm really not sure what has happened here and why this failed for you

The repository for this is open to the world and no password should be necessary.

What happens if you do a -

docker-compose rm
docker-compose pull

Or you do the following -

docker pull spurin/diveintoansible:ansible

Thanks


James

**Comment by spurin** [comment]
Also @igor-marinho please see the following thread.

https://github.com/docker/hub-feedback/issues/1484

If you have your own docker account try the 'docker login' approach and also, check the system time as per the other comment.

There shouldn't be any reason why you'd need to authenticate for a public image like this

**Comment by igor-marinho** [comment]
Bingo! it was because of docker login

Thank you.

**Comment by spurin** [comment]
Awesome @igor-marinho 

Glad to hear you've got it sorted.  As you're just starting out on this, I did just yesterday put a release candidate out for new images.

This includes the very latest version of Ansible.

If you wanted to try the course with this you could copy the docker-compose.yaml from the 'release-candidate' branch of this repo

**Comment by spurin** [comment]
Direct link to the file -

https://github.com/spurin/diveintoansible-lab/blob/release-candidate/docker-compose.yaml

The only difference is that the images have -rc (for release candidate) in the names.

In time, I will be switching the default images to these

**Comment by igor-marinho** [comment]
Thanks @spurin
