### ISSUE TITLE
Web Interface not opening https://localhost:1000/

### ISSUE THREAD

**Issue by AnkitSaxen** [spurin/diveintoansible-lab#20]
![Capture](https://user-images.githubusercontent.com/81170353/111999785-4f092080-8b43-11eb-945b-55ea14861766.PNG)

**Comment by AnkitSaxen** [comment]
ansadmin@ip-172-31-20-240:~/diveintoansible-lab$ cat .env
# sshd ports
UBUNTUC_PORT_SSHD=2221
UBUNTU1_PORT_SSHD=2222
UBUNTU2_PORT_SSHD=2223
UBUNTU3_PORT_SSHD=2224
CENTOS1_PORT_SSHD=2225
CENTOS2_PORT_SSHD=2226
CENTOS3_PORT_SSHD=2227

# ttyd (web terminal) ports
UBUNTUC_PORT_TTYD=7681
UBUNTU1_PORT_TTYD=7682
UBUNTU2_PORT_TTYD=7683
UBUNTU3_PORT_TTYD=7684
CENTOS1_PORT_TTYD=7685
CENTOS2_PORT_TTYD=7686
CENTOS3_PORT_TTYD=7687

# Shared config volume
CONFIG=/home/ansadmin/diveintoansible-lab/config

# Shared home directories
ANSIBLE_HOME=/home/ansadmin/diveintoansible-lab/ansible_home

**Comment by SpyderMYK** [comment]
I saw this response from @spurin in another issue.

In your docker-compose.yaml file, make the following edits to add LOCALHOST_OVERRIDE -

  portal:
    hostname: portal
    container_name: portal
    image: spurin/diveintoansible:portal
    environment:
     - NGINX_ENTRYPOINT_QUIET_LOGS=1
     - LOCALHOST_OVERRIDE=127.0.0.1
    depends_on:
     - centos1
     - centos2
     - centos3
     - ubuntu1
     - ubuntu2
     - ubuntu3
    ports:
     - "1000:80"
    networks:
     - diveinto.io
Do a ctrl-c on the running environment and then do a docker-compose up, this will fix your issue 👍

**Comment by AnkitSaxen** [comment]
Still not working..

**Comment by spurin** [comment]
Hi @AnkitSaxen,

Apologies, I tried to respond to this yesterday using the mobile interface but it looks like it didn't send.  Could you please revert your docker-compose.yaml file if you made changes for now.

Then, after restarting the lab, try http instead of https.

If the issue persists, please provide the output of 'docker ps -a' and your .env file.

Thanks

**Comment by AnkitSaxen** [comment]
ansadmin@Ansible:~/diveintoansible-lab$ sudo docker ps -a
CONTAINER ID   IMAGE                            COMMAND                  CREATED         STATUS                       PORTS     NAMES
408ee98abb8f   spurin/diveintoansible:portal    "/docker-entrypoint.…"   4 minutes ago   Exited (0) 2 minutes ago               portal
f2ea10ac48de   spurin/diveintoansible:ubuntu    "/lib/systemd/systemd"   8 minutes ago   Exited (130) 2 minutes ago             ubuntu3
8e6683547d80   spurin/diveintoansible:centos    "/usr/lib/systemd/sy…"   8 minutes ago   Exited (130) 2 minutes ago             centos3
f5fc430f3a5a   spurin/diveintoansible:dind      "dockerd-entrypoint.…"   8 minutes ago   Exited (0) 2 minutes ago               docker
f43465ebd04b   spurin/diveintoansible:centos    "/usr/lib/systemd/sy…"   8 minutes ago   Exited (130) 2 minutes ago             centos1
76d27f138708   spurin/diveintoansible:centos    "/usr/lib/systemd/sy…"   8 minutes ago   Exited (130) 2 minutes ago             centos2
98e83b227989   spurin/diveintoansible:ubuntu    "/lib/systemd/systemd"   8 minutes ago   Exited (130) 2 minutes ago             ubuntu1
e256ee471398   spurin/diveintoansible:ansible   "/lib/systemd/systemd"   8 minutes ago   Exited (130) 2 minutes ago             ubuntu-c
cc67f740e81c   spurin/diveintoansible:ubuntu    "/lib/systemd/systemd"   8 minutes ago   Exited (130) 2 minutes ago             ubuntu2
ansadmin@Ansible:~/diveintoansible-lab$

**Comment by AnkitSaxen** [comment]
Hi ,

Attaching the required output.

Still facing the same issue.
[output of .env.txt](https://github.com/spurin/diveintoansible-lab/files/6191365/output.of.env.txt)
[output of docker ps-a.txt](https://github.com/spurin/diveintoansible-lab/files/6191366/output.of.docker.ps-a.txt)
[yml.txt](https://github.com/spurin/diveintoansible-lab/files/6191367/yml.txt)

**Comment by spurin** [comment]
Thanks @AnkitSaxen,

Please share the output from the docker-compose up, also, can you give me specifics about the linux environment in which this is running?

**Comment by spurin** [comment]
Hi @AnkitSaxen,

Just following up on this.   Are you still having issues?

Thanks


James
