### ISSUE TITLE
stuck in bash loop

### ISSUE THREAD

**Issue by Rijo-ru** [spurin/diveintoansible-lab#24]
Hi!
After command 
```
for user in ansible root
do 
  for os in ubuntu centos
  do
    for instance in 1 2 3
    do 
    sshpass -f password.txt ssh-copy-id -o StrictHostKeyChecking=no ${user}@${os}${instance}
    done
  done
done
```
command execution stuck at first iteration 
![image](https://user-images.githubusercontent.com/34237769/115961206-b8bc8600-a558-11eb-8607-409ce83ee09d.png)

What's wrong with me? :(

**Comment by Rijo-ru** [comment]
I missed the command
`echo password > password.txt`
After this, all going good

**Comment by spurin** [comment]
Perfect @Rijo-ru 

Glad you've resolved this 👍

**Comment by Rijo-ru** [comment]
`echo password > password.txt`
