### ISSUE TITLE
Error Starting Service

### ISSUE THREAD

**Issue by bsalako87** [spurin/diveintoansible-lab#27]
![Screen Shot 2021-04-28 at 11 30 58 PM](https://user-images.githubusercontent.com/66656435/116499271-cab06880-a879-11eb-8da4-5501e4d6dc35.png)

**Comment by bsalako87** [comment]
@spurin please see above screenshot of the error I am getting.

Thank You

**Comment by spurin** [comment]
Hi @bsalako87 

Could you please share with me your .env file

Thanks!

**Comment by spurin** [comment]
Hi @bsalako87 

Assuming that this one was resolved.  If it's still outstanding, share the .env with me and I'll assist the fix for you.

Best Regards


James Spurin
