### ISSUE TITLE
Unable to login Ubuntu-C guest

### ISSUE THREAD

**Issue by hghisaidoobe** [spurin/diveintoansible-lab#28]
<img width="282" alt="Password not working Ubuntu" src="https://user-images.githubusercontent.com/83877218/117545770-7babc580-b027-11eb-99ab-eae896da592e.PNG">

Hi, I'm running on Ubuntu (20.4.2.0) as my host and all goes well until I must login into the ubuntu-c Ansible guest. No matter what password I use (I even changed the guest_pwd file to use a different password), none seem to work. Only get login incorrect message all the time. How can I solve this?

My .env file:

```
# Shared config volume
CONFIG=/users/hghisaidoobe/diveintoansible-lab/config

# Shared home directories
ANSIBLE_HOME=/users/hghisaidoobe/diveintoansible-lab/ansible_home
```

ansible_home does not get created after pull from git, have to create it manually (not running on Windows, so no mount here). I'm stuck here...

<img width="410" alt="Ansible path settings" src="https://user-images.githubusercontent.com/83877218/117546314-20c79d80-b02a-11eb-8ece-8a179b06c018.PNG">

**Comment by spurin** [comment]
Hi,

As your OS is Ubuntu, your Home directory should be /home instead of /users

Could you do a pwd from the diveintoansible-lab folder and update the config accordingly.

Then when you start the lab, it should read the correct config files and configure the user for you 👍

**Comment by hghisaidoobe** [comment]
That did the trick, totally forgot about that (being both a Windows and Linux user). Sometimes details do matter :-)

**Comment by spurin** [comment]
Awesome @hghisaidoobe 

Glad it's resolved and hope you enjoy the course 😁😁
