### ISSUE TITLE
Ubuntu Linux credentials

### ISSUE THREAD

**Issue by mroctober1011** [spurin/diveintoansible-lab#3]
My .env file has been modified to match my username and I have docker and docker compose installed. I'm able to make it to the Ansible lab screen when I browse to http://localhost:1000 but when I attempt to log into ubuntu-c with ansible and password, the credentials don't work. Any assistance would be greatly appreciated.
![2020-12-16_17-45](https://user-images.githubusercontent.com/36909427/102415738-ae94e480-3fc6-11eb-9501-8888f6617bff.png)
![2020-12-16_17-47](https://user-images.githubusercontent.com/36909427/102415830-dc7a2900-3fc6-11eb-9e34-0df4913654e4.png)

**Comment by mroctober1011** [comment]
I'm also having issues with permission in MAC OSX 10.14.6 (Mojave). It says its not able to create and mount the container though it has permissions to my home folder.
![Screen Shot 2020-12-16 at 12 56 54 PM](https://user-images.githubusercontent.com/36909427/102416108-3b3fa280-3fc7-11eb-87c6-844f45479620.png)

**Comment by spurin** [comment]
Hi Marcus,

More than happy to help.  It looks like you’re running on a Ubuntu system so should this be /home instead of /Users ?

**Comment by spurin** [comment]
Can you please share the errors you’re seeing on Mojave for this one.  

The output in the screenshot looks okay from what I can see with docker running the Ubuntu container as expected.

**Comment by mroctober1011** [comment]
::facepalm:: That should solve my issues on Linux. As for the MAC OS problem, I uploaded the wrong screenshot. Let me send the correct ones when I pull it back up here in a few minutes.

**Comment by mroctober1011** [comment]
Success!! In Linux, anyway. Thank you for the quick response too! Here is the MAC OS error.
![Screen Shot 2020-12-16 at 5 50 32 PM](https://user-images.githubusercontent.com/36909427/102419143-28c86780-3fcd-11eb-99db-b42fb9730117.png)

**Comment by spurin** [comment]
Perfect, glad it’s resolved and we’ll fix Mojave next 👍

**Comment by spurin** [comment]
This is interesting, could you run a pwd and share the directory path.

Did you happen to have Docker Desktop already installed or is this a new installation?

In Docker Desktop preferences, under resources there is a file share area.  I think it’s worth checking here if /Users is shared

**Comment by spurin** [comment]
Also, what happens if you just do a simple -

mkdir ansible_home

From the diveintoansible-lab folder?

**Comment by mroctober1011** [comment]
There was much more here before and sorry in advance..I didn't remove anything until it wasn't working if it counts. 
![Screen Shot 2020-12-16 at 6 46 21 PM](https://user-images.githubusercontent.com/36909427/102420029-1cdda500-3fcf-11eb-9540-7446283774c8.png)
![Screen Shot 2020-12-16 at 5 50 32 PM](https://user-images.githubusercontent.com/36909427/102420099-51e9f780-3fcf-11eb-8a47-36984c0e41d8.png)

**Comment by spurin** [comment]
I think by default, it should have /Users alongside some others,

Could you change that entry to /Users and then restart docker desktop (through the icon) and try again.

Also, as your marcus user, do you have any problems creating the ansible_home directory with a mkdir ansible_home

**Comment by mroctober1011** [comment]
I will but I'll be away for the rest of the night. To answer your last question, yes. It tells me permission denied as well. I'll send everything else tomorrow late morning/afternoon. Thank you again!

**Comment by spurin** [comment]
Sure, sync up tomorrow,

If you cannot create that directory ansible_home in the diveintoansible-lab folder you have a permissions problem going on.

You should be able to create any files/directories there without issue.

If you run the following, from the diveintoansible-lab folder we should be able to work out what is wrong -

pwd
id
ls -altrh
ls -ald ..
ls -ald ../..

Cheers

**Comment by mroctober1011** [comment]
Hello again. Here's a screen shot of the commands output you requested and file sharing settings in docker. ![image](https://user-images.githubusercontent.com/36909427/102555231-5cba9000-4094-11eb-9331-b2e3d286f573.jpeg)![image](https://user-images.githubusercontent.com/36909427/102555237-60e6ad80-4094-11eb-9ece-a49b32a47d59.png)![image](https://user-images.githubusercontent.com/36909427/102555243-63e19e00-4094-11eb-9aed-0455e92f73e7.jpeg)

**Comment by spurin** [comment]
Hi Marcus,

It looks like you’ve checked out the diveintoansible-lab folder as root, whilst you’re user is marcus.  As result, marcus can’t write to that directory which is the issue here.

**Comment by mroctober1011** [comment]
Forgive me for being a newbie but..how would I fix that? Should I start from the beginning under my own user name?

**Comment by piyushprbhange1** [comment]
i am not able to login to ansible. password is incorrect
![image](https://user-images.githubusercontent.com/71191496/102620094-7d055000-4163-11eb-97be-f406be9a477b.png)

**Comment by spurin** [comment]
Hey Marcus,

What OS are you running on here as we seem to have switched between a few different ones or, variations with VirtualBox.

In this case (for the screenshot above), I think the problem is a typo, there is an 's' in /home/p/sdiveintoansible-lab

Regarding the problem earlier on Mac, I suggest switching to root, removing the diveintoansible-lab folder, then, as the marcus user, clone the lab from gitlab, edit the .env updating the ANSIBLE_HOME and CONFIG variables accordingly and then retrying the docker-compose up

**Comment by mroctober1011** [comment]
That was me uploading the wrong screenshot again. But I've got Ubuntu working perfectly and I'm crusing through the labs. 

I'll definitely give your suggestions a try on Mojave and report back.

**Comment by mroctober1011** [comment]
Everything's working perfect. Thank you so much for your time and patience!
![Screen Shot 2020-12-18 at 2 53 04 PM](https://user-images.githubusercontent.com/36909427/102655963-28e97400-4141-11eb-8596-75f5e79a7acd.png)

**Comment by spurin** [comment]
Awesome!  I'm so glad you've got it working :-)  Hope you enjoy the rest of the course :-)
