### ISSUE TITLE
Unable to login to ubuntu-c

### ISSUE THREAD

**Issue by rohitud11** [spurin/diveintoansible-lab#30]
Hi There,

I have tried all the user name password combination of ansible and password but I am unable to login. Below attached is my env file. I have also run and modified the env file after running docker-compose rm and docker-compose up but still no luck. Any assistance would be appreaciated.
![image](https://user-images.githubusercontent.com/84450177/118805138-34dd8b80-b8c3-11eb-9b03-bc5f294c6234.png)

**Comment by spurin** [comment]
Hi @rohitud11,

We'll work this out and get it resolved.  Can you please tell me more about your environment.  Specifically, what version of Docker Desktop you're running, what the version of Windows is with the patch information (start/run/winver) and also, just to check, did you rename the folder above from diveintoansible-lab-master to diveintoansible-lab?

**Comment by rohitud11** [comment]
Hi There,

I was able to resolve the issue after a fresh install of docker desktop. Thanks again for your assistance.

Thanks,
Rohit
