### ISSUE TITLE
Not able to connect from ubuntu-c to any of other Hosts 

### ISSUE THREAD

**Issue by Hamnlet** [spurin/diveintoansible-lab#34]
Hi James,

When connecting from ubuntu-c to any of other hosts (ubunt1,2,3 or centos1,2,3) or vice-versa.

However I am able to ping the mentioned hosts or IPs. I was checking on each host and saw the port 22 is open., so what should be the issue here ?

![image](https://user-images.githubusercontent.com/79183072/120702484-1f9b5c00-c482-11eb-9313-ee3502a553c3.png)

![image](https://user-images.githubusercontent.com/79183072/120702937-ad774700-c482-11eb-8e19-bd98ba4c3ab9.png)

Here the version of docker and docker-compose as well as the configuration of the .env file,

![image](https://user-images.githubusercontent.com/79183072/120704142-380c7600-c484-11eb-8fbf-5d667daa19d5.png)

Any suggestion, please ?

**Comment by spurin** [comment]
Hi @Hamnlet 

This is quite peculiar, you're running Linux by the look of it, could you tell me more please about the parent OS?

Thanks


James

**Comment by Hamnlet** [comment]
Hi @spurin , I am using openSUSE Leap 15.3.

**Comment by spurin** [comment]
Do you know if selinux or any firewalls are active?

**Comment by spurin** [comment]
I've not tried the lab in Suse myself but this looks to me like there is a firewall/iptables blocking access.

Have a look through the following as this suggests to me that there may be a default firewall as part of the setup -

https://doc.opensuse.org/documentation/leap/security/html/book-security/cha-security-firewall.html

**Comment by Hamnlet** [comment]
H, Thank you for responding.
This is not tied to selinux, since its disabled.
I will check the above documentation you sent relative to security/firewall and will share later any progress.
Thanks,

**Comment by spurin** [comment]
Perfect thanks, as a quick check, does 

systemctl status firewalld

Show as running?

**Comment by Hamnlet** [comment]
Yes you got it.. The firewalld daemon was running, I just disabled it and try. 

I was able to get ssh connection between every docker images.

**Comment by spurin** [comment]
Wow!  Great to hear it's working for you @Hamnlet 

That's one strict default firewall 😁

Really hope you enjoy the rest of the course and appreciate your time working through the issue.

Best Regards


James

**Comment by Hamnlet** [comment]
Thank you very much James.
