### ISSUE TITLE
Issues with locating .env 

### ISSUE THREAD

**Issue by FlexKat4** [spurin/diveintoansible-lab#38]
Hello, I'm fairly novice with coding and very new to Ansible. I'm trying to install the lab to move forward but when completing the verification of the files in their paths, I'm missing the **env**. I'm not sure what commands to complete to locate it and successfully complete the steps to run the lab.

I'm stuck at the Validation and Configuration stages on https://github.com/spurin/diveintoansible-lab

Please let me know if there is any more info I can provide. Thank you

Here is an image below of what I have completed so far in the setup:
<img width="586" alt="Screen Shot 2021-06-23 at 11 31 14 AM" src="https://user-images.githubusercontent.com/86368312/123125713-c2f2e780-d416-11eb-86e2-5b1b040ebdbd.png">

**Comment by spurin** [comment]
Hi @FlexKat4 

It's a hidden file owing to the . at the start and it's shown in your screenshot.  If you 

vim .env

You should be good to go.  Let me know if i can help further or if I've misinterpreted this.

Cheers


James

**Comment by FlexKat4** [comment]
Hey James,

Thanks so much for getting back to me so quickly. I can now see the hidden file. Just for clarification on the next steps, I will need to rename/customize the CONFIG and ANSIBLE_HOME entries. 

I think I am running into some error so I think I need further clarification on the configuration step as well. I included a screenshot below of what everything looks like at the moment.

‘
Thank you,

Felix

**Comment by spurin** [comment]
Hi @FlexKat4,

Yep, thats correct.  Edit the file and then change the CONFIG and ANSIBLE_HOME entries to match your userid and then you should be good to go.

Any issues let me know and we'll resolve.

Thanks


James

**Comment by FlexKat4** [comment]
Alright, then I know I’m trying to achieve the right steps but I’m not quite sure how.

I am using MacOS, Terminal to complete the task.

The steps I took:
-Reverfiied that the file paths were there using ls -a /Users/felixmajor/diveintoansible-lab
- vim .env  and got the following below:


To confirm is this where the information found under macOS configuration should be placed with my information edited? 

Thank you,

Felix

**Comment by spurin** [comment]
Hi @FlexKat4,

I think you may have tried to share something with me but, unfortunately I don't see it?  That .env file, essentially you can edit it however you please (using vim or another editor) and in it, you should just need to change the entries that have james to your own userid, as you're on a mac as well there should be no other changes necessary.

Then, that's it, the file stays there and you can proceed to try bringing up the lab with -

```
docker-compose up
```

**Comment by FlexKat4** [comment]
Thanks for letting me know the image didn’t make it over. 
The previous image had the following message when following those steps.


E325: ATTENTION
Found a swap file by the name ".env.swp"
          owned by: felixmajor   dated: Wed Jun 23 13:31:30 2021
         file name: ~felixmajor/.env
          modified: YES
         user name: felixmajor   host name: Felixs-MacBook-Pro.local
        process ID: 3989
While opening file ".env"
      CANNOT BE FOUND
(1) Another program may be editing the same file.  If this is the case,
    be careful not to end up with two different instances of the same
    file when making changes.  Quit, or continue with caution.
(2) An edit session for this file crashed.
    If this is the case, use ":recover" or "vim -r .env"
    to recover the changes (see ":help recovery").
    If you did this already, delete the swap file ".env.swp"
    to avoid this message.

Swap file ".env.swp" already exists!
[O]pen Read-Only, (E)dit anyway, (R)ecover, (D)elete it, (Q)uit, (A)bort: 

Hopefully that comes through this time.

When typing in docker-compose up


felixmajor@Felixs-MacBook-Pro ~ % docker-compose up
can't find a suitable configuration file in this directory or any parent: not found
felixmajor@Felixs-MacBook-Pro ~ %

Thank you,

Flex

**Comment by spurin** [comment]
Hi Felix, so to resolve this, do the following -

At first it looks like the editing of the .env file was doing in a different directory so to resolve that, do this -

```
cd
rm -rf .env.swp
```

Then, let's change to the diveintoansible-lab folder and update the .env file from there -

```
cd ~/diveintoansible-lab
vim .env
```

You should see the contents of the file then and you just need to update the CONFIG and ANSIBLE_HOME entries with your userid, save the file and exit from vim.  Afterwards, whilst in that current directory, run -

```
docker-compose up
```

It should do some work and eventually, it will say a line that says Attaching to, at that point the lab is running and you can continue.

Best Regards


James Spurin

**Comment by FlexKat4** [comment]
Hey James,

Great news, I was able to get things to start attaching and move forward to setting up the lab.

Thank you so much for your assistance. I’ll be sure to reach out if there are other questions but I’m starting to get the handle on some things.

Best,

Flex

**Comment by spurin** [comment]
Perfect,

Thanks @FlexKat4, you should now be good in your browser to go to http://localhost:1000

I very much hope that you enjoy the course and if anything else pops up, you know where to find me.

Best Regards


James Spurin
