### ISSUE TITLE
[Enh Req] Open Terminals in new browser tab!

### ISSUE THREAD

**Issue by MartynKeigher** [spurin/diveintoansible-lab#41]
Quite a simple request here... request pretty much explains it! 

Would be nice to have the terminal sessions, listed on the portal 'home page', open in different web tabs. That way when\if i want to navigate back to the portal for any reason (maybe course links & resources), I don't have to disconnect from my existing terminal session.

While I know I could just open the portal in a new tab itself... this is more of a 'quality of life' tweak. 

Thanks. 

://mk

**Comment by spurin** [comment]
Nice request.

I refrained from it initially as some browsers reject tabs being opened (and show a pop-up in the title bar which some users may miss).

Setting the target to _blank_ in the hyperlink would do what is necessary for this to work.

I’ll see if I can add it as a portal environment variable like the LOCALHOST_OVERRIDE

Have just added this to my todo list, will keep you posted on progress on this here 👍

**Comment by spurin** [comment]
Hi @MartynKeigher 

Can you try this for me please, in your docker-compose.yaml, change the portal image so it's using -

diveintoansible-rc:portal

This is my release candidate branch.  Then, in your docker-compose.yaml, set the following variable -

- OPEN_LINKS_AS_TABS=1

Hopefully, this should then give the functionality you were looking for.  Let me know how you get on.

Cheers

**Comment by MartynKeigher** [comment]
Testing this now... will report back shortly!

**Comment by MartynKeigher** [comment]
Container is failing to start, on the rc build. All others spin up fine. exit code 1, fairly immediately.

**Comment by spurin** [comment]
Thanks @MartynKeigher 

Did you change any of the others or was it just the portal one?

The others, haven't been updated in a while so I'd only try the portal one with this.

Could you do another docker-pull as I did push a last minute fix, maybe docker hub hadn't propagated fully

**Comment by MartynKeigher** [comment]
Now it works! Nice little addition!!! 

Thank you for both considering and implementing it so quick!

**Comment by MartynKeigher** [comment]
Its in RC build & working, so will close this issue.
Up to the dev as to when it becomes part of master\main build.

**Comment by spurin** [comment]
@MartynKeigher 

Thanks for your help 👍
