### ISSUE TITLE
Unable to Login with user:ubuntu password:password

### ISSUE THREAD

**Issue by olivetech101** [spurin/diveintoansible-lab#51]
Hello Spurin, 

I tried changing the path within **_.env_** to one instructed in README but was again unable to login, with username **_ansible_** and the password as **_password_**

Sharing the details of my system below for your perusal:

- Host OS - Windows 10 
- Guest Os - Ubuntu20.04 (WSL2 aka Windows Subsystem Linux 2)

Previously I had cloned the repo within my WSL2 Ubuntu20.04 OS but made the below changes to the **_.env_** file

![WSL_ Ubuntu-20 04 -VisualStudioCode](https://user-images.githubusercontent.com/85228721/127759268-58b3ff39-1189-407c-8950-3dd7bb7d5164.png)

But still getting login error as shared below:
![FailedLoginUbuntu-c](https://user-images.githubusercontent.com/85228721/127759281-4f250c62-5199-4eee-a06d-d58308125540.png)

In my next attempt, I cloned the repo to 
![diveintoansible-lab](https://user-images.githubusercontent.com/85228721/127759326-4abdd52a-56fa-4994-9ab2-4df2ebfe7d9e.png)

_**and**_

made the following changes to the _**.env**_ file 
# Shared config volume
CONFIG=/mnt/c/Users/demo_user/diveintoansible-lab/ansible_home

# Shared home directories
ANSIBLE_HOME=/mnt/c/Users/demo_user/diveintoansible-lab/ansible_home

But still no luck. Requesting you to help me out to resolve this issue, please. Thanks

**Comment by olivetech101** [comment]
![WhatsAppImage](https://user-images.githubusercontent.com/85228721/127762981-5181ce3b-6d41-4810-a86d-50372d03c8c1.jpeg)

**Comment by spurin** [comment]
Hi @olivetech101 

Thanks for reaching out.  Could you please confirm for me, what your username is for logging into windows?  In the output I see both demo_user and olivetech.  For this, we need to tally up to the user in question.

Can you please try the following, we’re looking for the example that shows the username of ansible when run -

docker run --rm -v /host_mnt/c/users/demo_user/diveintoansible-lab/config:/config ubuntu cat /config/guest_name

docker run --rm -v /mnt/c/users/demo_user/diveintoansible-lab/config:/config ubuntu cat /config/guest_name

docker run --rm -v /c/users/demo_users/diveintoansible-lab/config:/config ubuntu cat /config/guest_name

docker run --rm -v /host_mnt/c/users/olivetech/diveintoansible-lab/config:/config ubuntu cat /config/guest_name

docker run --rm -v /mnt/c/users/olivetech/diveintoansible-lab/config:/config ubuntu cat /config/guest_name

docker run --rm -v /c/users/olivetech/diveintoansible-lab/config:/config ubuntu cat /config/guest_name

**Comment by olivetech101** [comment]
I am logging as demo_user into windows, I can **_definitely_** confirm that. Though a way to get past this, I have created a Ubuntu 20.04 VM using VirtualBox and trying to set up my env on virtualbox VM, hope that works. Will holler you in case I get stuck with it also.

**Comment by spurin** [comment]
Hi @olivetech101 

If you try those commands, it might be a quick fix for you.  I’ve seen sometimes that the variables can be case sensitive (noticed some uppercase in your tests).

I also have a prebuilt VM I can share with you if that helps?

**Comment by olivetech101** [comment]
![Screenshot from 2021-08-01 16-10-57](https://user-images.githubusercontent.com/85228721/127768377-d47aff6e-5b1b-43c5-b1df-7d639b630770.png)
Getting Invalid on my VM as well, so I reckon user is not the issue :S

**Comment by olivetech101** [comment]
Trying Again
![Screenshot from 2021-08-01 16-31-17](https://user-images.githubusercontent.com/85228721/127768417-f775493c-2dbb-499a-9fc0-e7e58bf46ce3.png)

**Comment by olivetech101** [comment]
![Screenshot from 2021-08-01 16-32-34](https://user-images.githubusercontent.com/85228721/127768451-e493adad-dbfe-474c-8cd5-86ebafe723ab.png)
Tried loggin with **_ubuntu_** and **_mayank_** my current user on ubuntu20.04 VM but no luck.

**Comment by olivetech101** [comment]
trying those commands suggested by you now. will come back with updates.

**Comment by spurin** [comment]
What username/password are you using?

**Comment by spurin** [comment]
Ahh I see above, the username and password you need is ansible password

**Comment by olivetech101** [comment]
Yes, I just observed that too. My bad, really appreciate your patience while trying to debug a silly error here. Again apologies. will kickstart the study now following oreilly course.

**Comment by spurin** [comment]
@olivetech101 no worries and my bad too, I jumped into this issue without fully digesting the subject.  Let’s also try and get this working on your desktop too.  If it’s not working, come back to me and we’ll get it resolved 👍

**Comment by olivetech101** [comment]
I can confirm it working on desktop too, I feel ashamed, gonna dive now in that pool now. 🙌

**Comment by spurin** [comment]
It’s all good @olivetech101 😁😁. Hope you enjoy the course! 🚀
