### ISSUE TITLE
docker exited with code 1 

### ISSUE THREAD

**Issue by mallilinux1980** [spurin/diveintoansible-lab#56]
hi James,

hope you're doing good. 

I was trying to set up lab today and it almost went through fine but failed with the last step, so not sure why. The screenshot is attached as well as my .env. [](url)

**Comment by mallilinux1980** [comment]
couldn't attach .env so here is the contents of the file.

# sshd ports
UBUNTUC_PORT_SSHD=2221
UBUNTU1_PORT_SSHD=2222
UBUNTU2_PORT_SSHD=2223
UBUNTU3_PORT_SSHD=2224
CENTOS1_PORT_SSHD=2225
CENTOS2_PORT_SSHD=2226
CENTOS3_PORT_SSHD=2227

# ttyd (web terminal) ports
UBUNTUC_PORT_TTYD=7681
UBUNTU1_PORT_TTYD=7682
UBUNTU2_PORT_TTYD=7683
UBUNTU3_PORT_TTYD=7684
CENTOS1_PORT_TTYD=7685
CENTOS2_PORT_TTYD=7686
CENTOS3_PORT_TTYD=7687

# Shared config volume
CONFIG=/users/mallik/diveintoansible-lab/config

# Shared home directories
ANSIBLE_HOME=/users/mallik/diveintoansible-lab/ansible_home

**Comment by spurin** [comment]
Hi @mallilinux1980 

It looks like you're on windows, firstly, for your host paths can you please try the following format -

/host_mnt/c/users/mallik

Then, let me know how you get on from there

**Comment by mallilinux1980** [comment]
thanks James.

this time no NGNIX related errors but still docker exited with 1.
![diveintoansible-lab1](https://user-images.githubusercontent.com/55889345/130793312-f630591c-fede-48fd-b532-7f00644f53e2.PNG)

**Comment by mallilinux1980** [comment]
let me retry it post "docker-compose rm' .

**Comment by spurin** [comment]
Could you also try -

docker-compose pull

Before issuing the up, just to verify that you're on the latest version.

By the way, is there anything else to note in your setup that might be different?  Use/configuration of WSL?

**Comment by mallilinux1980** [comment]
> let me retry it post "docker-compose rm' .

it worked.

thank you very much.

**Comment by spurin** [comment]
Awesome, thanks @mallilinux1980 for confirming.  For context, the Docker image uses the official dind image, for Docker in Docker.

One of the older images for Docker had some problems with certain OS versions but the later version fixed it, therefore, In this case it might have just been bad luck.

Glad it's resolved though and hope you enjoy the rest of the course

**Comment by mallilinux1980** [comment]
Hi James,
Hope you doing well. Need an advice from Ansible Master:)
Any opinion about this module though not quite active development since
2017? Or any other alternative exists?

https://dzone.com/articles/verifying-infrastructure-using-ansible
