### ISSUE TITLE
ansible/password not worked defaults after pulling the images from diveinto.io

### ISSUE THREAD

**Issue by shail8989** [spurin/diveintoansible-lab#6]
i have checked my .env and it has correct config & ansible_home dir also ~/guest_name, guest_password has setup for ansible/password as suggested but it is taking the defaults user name and password in the images from the hub diveinto.io .

it is worked defaults with root/root and there were no users in the ansible controls host (ubuntu-c) node after logged in by root user.

**Comment by spurin** [comment]
Hi @shail8989,

On Windows, you need to use the format detailed here - https://github.com/spurin/diveintoansible-lab#configuration

So for example, in your case, instead of 

```
ANSIBLE_HOME=C:/Users/TN387WW/diveintoansible-lab/ansible_home
CONFIG=C:/Users/TN387WW/diveintoansible-lab/config
```

Please try -

```
ANSIBLE_HOME=/host_mnt/c/users/tn387ww/diveintoansible-lab/ansible_home
CONFIG=/host_mnt/c/users/tn387ww/diveintoansible-lab/config
```

Let me know how you get on and if required, we'll troubleshoot further.  Thanks

**Comment by shail8989** [comment]
after changing the .env as suggested it shows me below errors..

C:\Users\TN387WW\diveintoansible-lab-master\diveintoansible-lab>docker-compose up
Creating ubuntu-c ...
Creating ubuntu1  ...
Creating centos1  ...
Creating ubuntu3  ...
Creating docker   ...
Creating ubuntu2  ...
Creating ubuntu3  ... error
Creating centos2  ...
Creating centos1  ... error
ERROR: for centos3  Cannot start service centos3: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/ansible_home/centos3/ansible': mkdir /host_mnt/c/users: operation not permitted

ERROR: for ubuntu3  Cannot start service ubuntu3: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/config': mkdir /host_mnt/c/users: operation not permitted

ERROR: for centos1  Cannot start service centos1: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/config': Creating ubuntu1  ... error
Creating ubuntu2  ... error
ERROR: for centos2  Cannot start service centos2: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/ansible_home/centos2/root': mkdir /host_mnt/c/users: operation not permitted

Creating ubuntu-c ... error
Creating docker   ... error

ERROR: for ubuntu1  Cannot start service ubuntu1: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/ansible_home/ubuntu1/root': mkdir /host_mnt/c/users: operation not permitted

ERROR: for docker  Cannot start service docker: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/ansible_home/shared': mkdir /host_mnt/c/users: operation not permitted

ERROR: for ubuntu-c  Cannot start service ubuntu-c: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/ansible_home/ubuntu-c/ansible': mkdir /host_mnt/c/users: operation not permitted

ERROR: for centos3  Cannot start service centos3: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/ansible_home/centos3/ansible': mkdir /host_mnt/c/users: operation not permitted

ERROR: for ubuntu3  Cannot start service ubuntu3: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/config': mkdir /host_mnt/c/users: operation not permitted

ERROR: for centos1  Cannot start service centos1: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/config': mkdir /host_mnt/c/users: operation not permitted

ERROR: for centos2  Cannot start service centos2: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/ansible_home/centos2/root': mkdir /host_mnt/c/users: operation not permitted

ERROR: for ubuntu2  Cannot start service ubuntu2: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/ansible_home/ubuntu2/ansible': mkdir /host_mnt/c/users: operation not permitted

ERROR: for ubuntu1  Cannot start service ubuntu1: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/ansible_home/ubuntu1/root': mkdir /host_mnt/c/users: operation not permitted

ERROR: for docker  Cannot start service docker: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/ansible_home/shared': mkdir /host_mnt/c/users: operation not permitted

ERROR: for ubuntu-c  Cannot start service ubuntu-c: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/ansible_home/ubuntu-c/ansible': mkdir /host_mnt/c/users: operation not permitted
ERROR: Encountered errors while bringing up the project.

C:\Users\TN387WW\diveintoansible-lab-master\diveintoansible-lab>

**Comment by spurin** [comment]
Hi @shail8989,

Can you please confirm for me, the version of Windows and Docker Desktop that you're using.

Cheers


James

**Comment by shail8989** [comment]
hi james, 

yes sure..

windows 10 and docker desktop version as below- 
docker run -v /host_mnt/c:/test --rm spurin/diveintoansible:ubuntu ls /test

also i tested this and worked well.
docker run -v /host_mnt/c:/test --rm spurin/diveintoansible:ubuntu ls /test

C:\Users\TN387WW\diveintoansible-lab-master\diveintoansible-lab>docker run -v /host_mnt/c:/test --rm spurin/diveintoansible:ubuntu ls /test
$WINDOWS.~BT
$Windows.~WS
DataMigration
Dell
ESD
ETH
Fuseki
Intel
Kubernetes
Lotus
MAINTENANCE
MAMP
MAMPPRO
MATS
MinGW
OneDriveTemp
PerfLogs
Phonebackup
Program Files
Program Files (x86)
ProgramData
TOD
Talend
Users
VC_RED.MSI
VC_RED.cab
Windows
data
eula.1028.txt
eula.1031.txt
eula.1033.txt
eula.1036.txt
eula.1040.txt
eula.1041.txt
eula.1042.txt
eula.2052.txt
eula.3082.txt
globdata.ini
install.exe
install.ini
install.res.1028.dll
install.res.1031.dll
install.res.1033.dll
install.res.1036.dll
install.res.1040.dll
install.res.1041.dll
install.res.1042.dll
install.res.2052.dll
install.res.3082.dll
logs
minishift-1.34.2-windows-amd64
pending.un
vcredist.bmp
xampp

**Comment by shail8989** [comment]
C:\Users\TN387WW\diveintoansible-lab-master\diveintoansible-lab>docker --version
Docker version 20.10.2, build 2291f61

**Comment by spurin** [comment]
Thanks, I don't see your windows version in that output unfortunately but the rest is helpful, could you please let me know.  Also, run the following -

```
docker run -v /host_mnt/c/users:/test --rm spurin/diveintoansible:ubuntu ls /test
docker run -v /host_mnt/c/users/tn387ww:/test --rm spurin/diveintoansible:ubuntu ls /test
```

Cheers

**Comment by shail8989** [comment]
it said that files are already exists as below errors 

C:\Users\TN387WW\diveintoansible-lab-master\diveintoansible-lab>docker run -v /host_mnt/c/users:/test --rm spurin/diveintoansible:ubuntu ls /test
docker: Error response from daemon: error while creating mount source path '/host_mnt/c/users': mkdir /host_mnt/c/users: file exists.

C:\Users\TN387WW\diveintoansible-lab-master\diveintoansible-lab>docker run -v /host_mnt/c/users/tn387ww:/test --rm spurin/diveintoansible:ubuntu ls /test
docker: Error response from daemon: error while creating mount source path '/host_mnt/c/users/tn387ww': mkdir /host_mnt/c/users: file exists.

C:\Users\TN387WW\diveintoansible-lab-master\diveintoansible-lab>

**Comment by spurin** [comment]
Thanks @shail8989,

I've seen someone have this issue or something similar before, what version of Windows is it?

**Comment by shail8989** [comment]
windows 10
version 1803(OS build 17134.1845)

**Comment by spurin** [comment]
Thanks @shail8989,

Okay this is confirmed, I'm very confident in the issue that you're seeing here.  The WSL (Windows Subsystem For Linux) is v1 on this build of Windows.  Upgrading your version of Windows would fix this but, I believe there is another way we can get this working if you don't mind working through some testing with me.

Would you please share the output of -

```
docker run -v /c/users:/test --rm spurin/diveintoansible:ubuntu ls /test
```

**Comment by shail8989** [comment]
yup sure, no problem, i wanted to fix it anyhow and wanted to login as described.

output below-->
C:\Users\TN387WW\diveintoansible-lab-master\diveintoansible-lab>docker run -v /c/users:/test --rm spurin/diveintoansible:ubuntu ls /test
Default
Public
TN387WW

**Comment by spurin** [comment]
Thanks, so next -

```
docker run -v /c/users/tn387ww:/test --rm spurin/diveintoansible:ubuntu ls /test
docker run -v /c/users/tn387ww/diveintoansible-lab/config:/test --rm spurin/diveintoansible:ubuntu ls /test
```

**Comment by shail8989** [comment]
for the first one-->

C:\Users\TN387WW\diveintoansible-lab-master\diveintoansible-lab>docker run -v /c/users/tn387ww:/test --rm spurin/diveintoansible:ubuntu ls /test
3D Objects
AppData
Contacts
Desktop
Documents
Downloads
Favorites
InstallAnywhere
Last session TN387WW.prj
Links
MicrosoftEdgeBackups
Music
OneDrive
OneDrive - EY
Pictures
Roaming
Saved Games
Searches
Videos
VirtualBox VMs
abc
c
diveintoansible-lab
diveintoansible-lab-master
diveintoansible-lab-master.zip
donation-export.sql
eclipse
eclipse-workspace
export.sql
frankie
getting-started
mycode
package-lock.json
shell_project
source
sqlplus
terraform
udemy-docker-mastery-master
vagrant
volunteer-export.sql
yash


for the second--> 

C:\Users\TN387WW\diveintoansible-lab-master\diveintoansible-lab>docker run -v /c/users/tn387ww/diveintoansible-lab/config:/test --rm spurin/diveintoansible:ubuntu ls /test

no output..

**Comment by spurin** [comment]
I think the diveintoansible-lab-master might need to be swapped with diveintoansible-lab, what do you get on this -

```
docker run -v /c/users/tn387ww/diveintoansible-lab:/test --rm spurin/diveintoansible:ubuntu ls /test
docker run -v /c/users/tn387ww/diveintoansible-lab-master/config:/test --rm spurin/diveintoansible:ubuntu ls /test
```

**Comment by shail8989** [comment]
I cleaned up everything and again setup like below...

PS C:\Users\TN387WW> cd .\diveintoansible-lab\
PS C:\Users\TN387WW\diveintoansible-lab> ls


    Directory: C:\Users\TN387WW\diveintoansible-lab


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         1/8/2021   8:10 AM                config
-a----         1/8/2021   8:16 AM            658 .env
-a----         1/8/2021   8:04 AM         159521 DiveIntoAnsible_Cover.png
-a----         1/8/2021   8:04 AM           4061 docker-compose.yaml
-a----         1/8/2021   8:04 AM           5873 README.md


PS C:\Users\TN387WW\diveintoansible-lab> cat .\.env
# sshd ports
UBUNTUC_PORT_SSHD=2221
UBUNTU1_PORT_SSHD=2222
UBUNTU2_PORT_SSHD=2223
UBUNTU3_PORT_SSHD=2224
CENTOS1_PORT_SSHD=2225
CENTOS2_PORT_SSHD=2226
CENTOS3_PORT_SSHD=2227

# ttyd (web terminal) ports
UBUNTUC_PORT_TTYD=7681
UBUNTU1_PORT_TTYD=7682
UBUNTU2_PORT_TTYD=7683
UBUNTU3_PORT_TTYD=7684
CENTOS1_PORT_TTYD=7685
CENTOS2_PORT_TTYD=7686
CENTOS3_PORT_TTYD=7687

# Shared config volume
#CONFIG=/Users/tn387ww/diveintoansible-lab/config
# Shared home directories
#ANSIBLE_HOME=/Users/tn387ww/diveintoansible-lab/ansible_home

ANSIBLE_HOME=/host_mnt/c/users/tn387ww/diveintoansible-lab/ansible_home
CONFIG=/host_mnt/c/users/tn387ww/diveintoansible-lab/config
PS C:\Users\TN387WW\diveintoansible-lab>
----------------------------------------------------------------
it give me permission error ..

PS C:\Users\TN387WW\diveintoansible-lab> docker-compose up
Creating network "diveinto.io" with the default driver
Creating ubuntu3 ...
Creating centos1 ...
Creating centos3 ...
Creating docker   ... error
Creating centos1  ... error
Creating ubuntu2  ...
Creating centos2  ...
Creating ubuntu1  ...

ERROR: for docker  Cannot start service docker: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/ansible_home/shared': mkdir /host_mnt/c/users: operation not permitted

Creating ubuntu3  ... error
operation not permitted
Creating ubuntu2  ... error
ERROR: for centos2  Cannot start service centos2: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/config': mkdir /host_mnt/c/users: operation not permitted
Creating centos3  ... error
ERROR: for ubuntu2  Cannot start service ubuntu2: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/ansible_home/ubuntu2/ansible': mkdir /host_mnt/c/users: operation not permitted

ERROR: for ubuntu3  Cannot start service ubuntu3: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/ansible_home/shared': mkdir /host_mnt/c/users: operatCreating ubuntu-c ... error

ERROR: for centos3  Cannot start service centos3: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/ansible_home/centos3/root': mkdir /host_mnt/c/users: operation not permitted

ERROR: for ubuntu-c  Cannot start service ubuntu-c: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/ansible_home/ubuntu-c/ansible': mkdir /host_mnt/c/uCreating ubuntu1  ... error

ERROR: for ubuntu1  Cannot start service ubuntu1: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/ansible_home/ubuntu1/root': mkdir /host_mnt/c/users: operation not permitted

ERROR: for docker  Cannot start service docker: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/ansible_home/shared': mkdir /host_mnt/c/users: operation not permitted

ERROR: for centos1  Cannot start service centos1: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/ansible_home/centos1/root': mkdir /host_mnt/c/users: operation not permitted

ERROR: for centos2  Cannot start service centos2: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/config': mkdir /host_mnt/c/users: operation not permitted

ERROR: for ubuntu2  Cannot start service ubuntu2: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/ansible_home/ubuntu2/ansible': mkdir /host_mnt/c/users: operation not permitted

ERROR: for ubuntu3  Cannot start service ubuntu3: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/ansible_home/shared': mkdir /host_mnt/c/users: operation not permitted

ERROR: for centos3  Cannot start service centos3: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/ansible_home/centos3/root': mkdir /host_mnt/c/users: operation not permitted

ERROR: for ubuntu-c  Cannot start service ubuntu-c: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/ansible_home/ubuntu-c/ansible': mkdir /host_mnt/c/users: operation not permitted

ERROR: for ubuntu1  Cannot start service ubuntu1: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/ansible_home/ubuntu1/root': mkdir /host_mnt/c/users: operation not permitted
ERROR: Encountered errors while bringing up the project.
PS C:\Users\TN387WW\diveintoansible-lab>

------------------------------------------------
also here is the output for both cmd

PS C:\Users\TN387WW\diveintoansible-lab> docker run -v /c/users/tn387ww/diveintoansible-lab:/test --rm spurin/diveintoansible:ubuntu ls /test
DiveIntoAnsible_Cover.png
README.md
config
docker-compose.yaml

PS C:\Users\TN387WW\diveintoansible-lab> docker run -v /c/users/tn387ww/diveintoansible-lab-master/config:/test --rm spurin/diveintoansible:ubuntu ls /test
PS C:\Users\TN387WW\diveintoansible-lab>

(no output to second as this dir is removed)

**Comment by spurin** [comment]
Great, so that is now looking as expected.  Please be aware, this is going to be trial and error as I've seen this issue once before, but, the person in question chose to update Windows rather than going down this route.  Let's try this first and then you have the upgrade, as a backup option -

I have a different branch, which has a variant of the docker-compose.yaml file.  Can you please take this file, and replace it with your own -

https://github.com/spurin/diveintoansible-lab/blob/nonpersistent_home/docker-compose.yaml

Then, try the docker-compose up and report the output

**Comment by shail8989** [comment]
i have tried with new .yaml file but it has same error as below also check my .env incase i am in doubt.

PS C:\Users\TN387WW\diveintoansible-lab> docker-compose up
Creating docker   ... error
Creating ubuntu-c ...
Creating centos3  ...
Creating ubuntu1  ...
Creating ubuntu-c ... error
Creating ubuntu3  ...
Creating centos1  ...
Creating ubuntu2  ...

ERROR: for docker  Cannot start service docker: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/ansible_home/shared': mkdir /host_mnt/c/users: operation not permitted

Creating centos1  ... error
ab/ansible_home/shared': mkdir /host_mnt/c/users: operation not permitted

ERROR: for centos1  Cannot start service centos1: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-labCreating centos2  ... error

Creating ubuntu1  ... error
/config': mkdir /host_mnt/c/users: operation not permitted

ERROR: for centos2  Cannot start service centos2: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/ansible_home/shared': mkdir /host_mnt/c/users: operation not permitted
Creating centos3  ... error
ERROR: for ubuntu1  Cannot start service ubuntu1: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/config': mkdir /host_mnt/c/users: operation not permitted

ERROR: for ubuntu3  Cannot start service ubuntu3: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/config': mkdir /host_mnt/c/users: operation not permitted

ERROR: for centos3  Cannot start service centos3: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/ansible_home/shared': mkdir /host_mnt/c/users: operation not permitted

ERROR: for docker  Cannot start service docker: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/ansible_home/shared': mkdir /host_mnt/c/users: operation not permitted

ERROR: for ubuntu-c  Cannot start service ubuntu-c: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/ansible_home/shared': mkdir /host_mnt/c/users: operation not permitted

ERROR: for centos1  Cannot start service centos1: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/config': mkdir /host_mnt/c/users: operation not permitted

ERROR: for ubuntu2  Cannot start service ubuntu2: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/config': mkdir /host_mnt/c/users: operation not permitted

ERROR: for centos2  Cannot start service centos2: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/ansible_home/shared': mkdir /host_mnt/c/users: operation not permitted

ERROR: for ubuntu1  Cannot start service ubuntu1: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/config': mkdir /host_mnt/c/users: operation not permitted

ERROR: for ubuntu3  Cannot start service ubuntu3: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/config': mkdir /host_mnt/c/users: operation not permitted

ERROR: for centos3  Cannot start service centos3: error while creating mount source path '/host_mnt/c/users/tn387ww/diveintoansible-lab/ansible_home/shared': mkdir /host_mnt/c/users: operation not permitted
ERROR: Encountered errors while bringing up the project.
PS C:\Users\TN387WW\diveintoansible-lab> cat .env
# sshd ports
UBUNTUC_PORT_SSHD=2221
UBUNTU1_PORT_SSHD=2222
UBUNTU2_PORT_SSHD=2223
UBUNTU3_PORT_SSHD=2224
CENTOS1_PORT_SSHD=2225
CENTOS2_PORT_SSHD=2226
CENTOS3_PORT_SSHD=2227

# ttyd (web terminal) ports
UBUNTUC_PORT_TTYD=7681
UBUNTU1_PORT_TTYD=7682
UBUNTU2_PORT_TTYD=7683
UBUNTU3_PORT_TTYD=7684
CENTOS1_PORT_TTYD=7685
CENTOS2_PORT_TTYD=7686
CENTOS3_PORT_TTYD=7687

# Shared config volume
#CONFIG=/Users/tn387ww/diveintoansible-lab/config
# Shared home directories
#ANSIBLE_HOME=/Users/tn387ww/diveintoansible-lab/ansible_home

ANSIBLE_HOME=/host_mnt/c/users/tn387ww/diveintoansible-lab/ansible_home
CONFIG=/host_mnt/c/users/tn387ww/diveintoansible-lab/config
PS C:\Users\TN387WW\diveintoansible-lab>

**Comment by spurin** [comment]
Could you please change ANSIBLE_HOME and CONFIG so that the prefix is /c/users and try again

**Comment by shail8989** [comment]
finally it worked now after setting up the ansible_home and config to /c/users..!!

thanks spurin..!! continue to the learning...

**Comment by spurin** [comment]
@shail8989 great to hear it’s working for you.

Something you need to be aware of... owing to the version of Windows that you’re on, you won’t have persistent data in the ansible or root users home directory using the workaround.  

Reason being, that version you’re on leaves any directories that are passed to docker as completely open.  SSH rejects the permissions and it won’t work for passwordless ssh.

The version of the file that I provided you turns off the volume mounting for both the ansible and root user.

If you down/up the environment, you’ll be fine, but, if you do a docker-compose rm, followed by an up, you’ll wipe the data in the ansible or root homedirectories.  As long as you don’t remove the lab, you’ll be fine.

Alternatively, as you do the course, use the folder /shared for storing any data and this will persist and survive, a complete removal and recreation of the lab.

Make sense?

**Comment by shail8989** [comment]
yup, i understand it..i take care of it.
thank you for your help and guidance..!!

**Comment by spurin** [comment]
Awesome, thanks @shail8989 closing the issue.  Enjoy the course :-)
