### ISSUE TITLE
Windows 10 - Certificate error in docker-compose up

### ISSUE THREAD

**Issue by DanishNazirMalik** [spurin/diveintoansible-lab#65]
I am getting the following error:
C:\Users\31983170\diveintoansible-lab>docker-compose up
Pulling ubuntu-c (spurin/diveintoansible:ansible)...
ERROR: Get "https://registry-1.docker.io/v2/": x509: certificate is valid for *.wolterskluwer.cloud, not registry-1.docker.io

My docker details:
C:\>docker version
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:58:50 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by DanishNazirMalik** [comment]
Hi Spurin,
The error is still outstanding.
Yeah, I am using my corporate laptop.

**Comment by spurin** [comment]
Hi @DanishNazirMalik 

Are you aware of corporate proxies that you need to use?  It looks like your system is blocking the Docker registry
