### ISSUE TITLE
Too many spaces in docker-compose.yaml

### ISSUE THREAD

**Issue by mraczka** [spurin/diveintoansible-lab#7]
In docker-compose.yaml there are too many spaces which causes error when trying to run docker-compose up.

**Comment by spurin** [comment]
Hi @mraczka,

Interesting that you've had this issue, do you mind please sharing with me more details, specifically, OS, version of docker and docker-compose.

Thanks

**Comment by mraczka** [comment]
Hi.
I've just tried to reproduce my problem but it seems like it's gone. Some other steps must have solved it - probably docker-compose upgrade. Nevertheless everything works as expected now.
