### ISSUE TITLE
Lab Issues - Cgroups v2, WSL (using alternative subsystems) - Potentially fixed

### ISSUE THREAD

**Issue by spurin** [spurin/diveintoansible-lab#72]
Hi All,

Hope you are doing well.  Am tagging you in the issue as at some point in the past, we've discussed issues that you've faced when running the diveintoansible-lab.

In summary, these issues fall into the following categories -

1) You're using a newer distribution of Linux such as >=Fedora 31, Debian Bullseye, Kubuntu etc which makes use of the newer cgroups v2.  The fix for this was the implementation of a Kernel boot option to switch cgroups to v1, a reboot, removal of the existing lab (docker-compose rm) and a fresh start (docker-compose up).

2) You're running the Windows Subsystem for Linux and have opted to use one of other options available as the subsystem.  For example, Ubuntu, Suse etc.  In these cases, to make the lab work the fix was a manual mount command that had to be executed before executing the docker-compose up

After a lot of work and low level debugging/compiling with systemd, I am pleased to let you know that I have just finialised new images for the lab that I believe will automatically work with the scenarios above as well as the traditional environments (i.e. a baseline Windows/Mac/Linux installation).  So far my testing looks positive!

As well as this, I think I've also found a happy medium across platforms that mean that you don't have to edit the .env file and add your user paths in.

These images are referenced in the https://github.com/spurin/diveintoansible-lab/tree/release-candidate branch.  If you're interested and don't mind, I would very much appreciate your help with testing and verifying if the issues above have been put to rest.  

If you use the docker-compose.yaml and the .env file from this branch, it should then be a case of just running -

```
docker-compose rm
docker-compose pull
docker-compose up
```

A good check to do will also be a docker stop/start to verify that the lab can also be restarted with issue.

```
<ctrl-c the running lab>
docker-compose up
```

Please let me know how you get on and any information relating to your platform.  Of course, this is also open to all watchers, those who have seen the pinned issue and anyone else who can help 🙏

Many Thanks

James

@Priyanka-Cloud-Infinite @steevi @WindsOfHades @vanzod @carlosdoliveira @anshad666 @yokodev @bcookatpcsd @k0b @oscarmparedes

**Comment by spurin** [comment]
Related - https://github.com/spurin/diveintoansible-lab/issues/73

**Comment by drpott** [comment]
champion!

its working on fedora-34

dan@LAT7490 ~/diveintoansible-lab (release-candidate) $ docker-compose up
Creating centos2  ... done
Creating ubuntu2  ... done
Creating docker   ... done
Creating ubuntu1  ... done
Creating centos3  ... done
Creating ubuntu3  ... done
Creating centos1  ... done
Creating ubuntu-c ... done
Creating portal   ... done
Attaching to ubuntu2, centos2, docker, ubuntu3, ubuntu1, centos1, ubuntu-c, centos3, portal

thanks heaps

**Comment by spurin** [comment]
Thanks @drpott - appreciated

**Comment by MaximUltimatum** [comment]
@spurin - Thank you so much for working on this!
I have done some testing on the podman-compose branch.
Upon running
`sudo podman-compose -t identity -f podman-compose.yaml up`
The containers error out with
`Error: statfs /home/admin/diveintoansible-lab/ansible_home/shared: no such file or directory`
I've reviewed the earlier videos in your ansible course to see if these are manually created, but as best I can tell the mounted ansible_home folder was created by the container setup. Am I missing anything obvious?

**Comment by spurin** [comment]
Closing this issue, in testing I've been successful with this on both Mac M1/x86, Windows 10 & 11 (using all subsystems), Fedora 34 & 35 and Debian Bullseye.

If any of you encounter an issue please let me know and I'll re-open 😀
