### ISSUE TITLE
ERROR: Version in "./docker-compose.yaml" is unsupported. You might be seeing this error because you're using the wrong Compose file version.

### ISSUE THREAD

**Issue by baditaflorin** [spurin/diveintoansible-lab#74]
/diveintoansible-lab$ docker-compose up
ERROR: Version in "./docker-compose.yaml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**Comment by baditaflorin** [comment]
Fixed by deleting the old version that I go using sudo apt install docker-compose and getting the latest version via

**Comment by spurin** [comment]
Thanks for confirming @baditaflorin 

I recommend Docker-compose 1.29 or the newer version 2 (which coincidently, Docker desktop on Windows is now using)
