### ISSUE TITLE
user ansible does not exists in the docker image ubuntu-c

### ISSUE THREAD

**Issue by baditaflorin** [spurin/diveintoansible-lab#75]

**Comment by spurin** [comment]
Hi @baditaflorin 

Hope you're well.  The image intentionally doesn't have the ansible user.  During init, it's created as required.

If this is not happening for you, can you please update your .env file entries for following -

CONFIG=./config
ANSIBLE_HOME=./ansible_home

Ctrl-c the lab if it's running and restart.  This should then resolve any issues 👍

**Comment by spurin** [comment]
Hi @baditaflorin 

Closing this issue, please let me know if you're still having problems.


Thanks

James Spurin
