### ISSUE TITLE
@spurin I am facing the same issue as below but on a mac system. any work around for the same

### ISSUE THREAD

**Issue by MohanDV** [spurin/diveintoansible-lab#84]
@spurin I am facing the issue as below but on a mac system. any work around for the same ? 

Attaching to centos1, centos2, centos3, docker, portal, ubuntu-c, ubuntu1, ubuntu2, ubuntu3                                                                                                 
ubuntu3 exited with code 255                                                                                                                                                                
ubuntu-c exited with code 255                                                                                                                                                               
ubuntu2 exited with code 255                                                                                                                                                                
ubuntu1 exited with code 255                                                                                                                                                                
portal    | 2021/12/13 14:17:06 [emerg] 1#1: host not found in upstream "ubuntu1" in /etc/nginx/conf.d/default.conf:45                                                                      
portal    | nginx: [emerg] host not found in upstream "ubuntu1" in /etc/nginx/conf.d/default.conf:45                                                                                        
portal exited with code 1

**Comment by spurin** [comment]
Hi @MohanDV 

This should now be resolved as a new version of the lab was released that specifically addresses this.  If you had a version of the lab prior to the 6th December then it will be the old version (that was recently broken by the latest update of Docker Desktop for Mac).

If so, could you please take the latest version from the main branch, specifically you want the docker-compose.yaml and the .env file, the following commands will work if you originally checkout out using git -

```
git reset --hard
git checkout master
git pull
docker-compose rm
docker-compose pull
docker-compose up
```

Please let me know how you get on :-)

**Comment by spurin** [comment]
@MohanDV closing the issue, if there's still any problems let me know and I'll re-open.

Best Regards

- James

**Comment by Zachnjue** [comment]
Hi @spurin. The above instructions have worked on my end since i was experiencing the same issue. Thanks
