### ISSUE TITLE
docker-compose up error in CentOS 

### ISSUE THREAD

**Issue by ash-rawat** [spurin/diveintoansible-lab#85]
Hi,

i am getting below error while using docker-compose up

ERROR: Version in "./docker-compose.yaml" is unsupported. You might be seeing this error because you're using the wrong│                                                                                                                      Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under│                                                                                                                      the `services` key, or omit the `version` key and place your service definitions at the root of the file to use versio│                                                                                                                     n 1.                                                                                                                   │                                                                                                                     For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

could you please help me out in this

**Comment by ash-rawat** [comment]
and my docker-compose version is

docker-compose --version                                               │
docker-compose version 1.21.0, build 5920eb0

**Comment by spurin** [comment]
Hi @ash-rawat 

Your docker-compose version is too old, this sometimes happen when you do a yum/apt install.

If you revert the installation, and then grab one of the binaries from the releases section of the docker-compose GitHub page, you should be good to go!

In the course lab setup video, in the Linux section this is what I do.  If you're following this along without the course, just grabbing a newer binary will get you where you need to be 😁

Let me know how you get on and if you have any problems.

Best Regards


James
