### ISSUE TITLE
ssh still requesting pwd after sharing public keys

### ISSUE THREAD

**Issue by SantiProven** [spurin/diveintoansible-lab#9]
Hello James,

I'm using docker in Windows 10. I've deployed the lab environment as described and it looks working fine.
Nevertheless after copying the public key from ubuntu-c to the authorized_keys file of ubuntu1 when doing ssh the pwd is still being requested:

_ansible@ubuntu-c:~$ ssh ansible@ubuntu1
ansible@ubuntu1's password: 
Last login: Mon Dec 21 09:39:51 2020 from 172.18.0.9
ansible@ubuntu1:~$ cd .ssh/
ansible@ubuntu1:~/.ssh$ ll
total 5
drwxrwxrwx 1 ansible ansible    0 Dec 21 09:59 ./
drwxrwxrwx 1 root    root    4096 Dec 21 10:57 ../
-rwxr-xr-x 1 ansible ansible  570 Dec 21 09:39 authorized_keys*
ansible@ubuntu1:~/.ssh$ cat authorized_keys 
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDP1bpGcNM+M0BuX+jFYQdpHPdJev9IlnWt14JxAqLulpgAumxTTG2NYrx6XaWYmUUyq1x10uLHX6QGLS5rqcvttOU/rQLlCVLdoB/ATWJa+k9x71Y5ocfvp7uMMz8VMdPitOEojcFoF6EK+Few08ArYduN5O51LZmbDAFvIKEDUr3vBWdorSk+xwS3dXnDQvdu3tL0Kj+xum3rGyurl9QqWmtWaqdueKFO1C9okOcLjwGy6+72yIJ1QOVr6hcrEyMbhbytIIXmqaQHvdKbxvoNLqJsWlJ0If/QNqdVko/WFc/ll27m2Bevh8aas6MNjdrP0H7vatjvEB4Crt6/U+Fr2XOlwzF9FlJDIxIX6w4ouvRUKiwOXNpCkhOZj4AuMeoiYnWVBzV0J2AZh3ltb+E7bUnmlrPVDTveJA9QumlKslR8UxSrBMp9mSof8dywo6WgM+oDbgJkXBpZkKdy9V+ToHSRzWBdwgHmMv82axoKLsujQGD3Hdyb8SFzmP6/nls= ansible@ubuntu-c
ansible@ubuntu1:~/.ssh$ exit
logout
Connection to ubuntu1 closed.
ansible@ubuntu-c:~$ cd .ssh/
ansible@ubuntu-c:~/.ssh$ ll
total 13
drwxrwxrwx 1 ansible ansible 4096 Dec 21 09:39 ./
drwxrwxrwx 1 root    root    4096 Jan 12 10:58 ../
-rwxr-xr-x 1 ansible ansible 2602 Dec 21 09:37 id_rsa*
-rwxr-xr-x 1 ansible ansible  570 Dec 21 09:37 id_rsa.pub*
-rwxr-xr-x 1 ansible ansible  444 Dec 21 09:39 known_hosts*
ansible@ubuntu-c:~/.ssh$ cat id_rsa.pub 
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDP1bpGcNM+M0BuX+jFYQdpHPdJev9IlnWt14JxAqLulpgAumxTTG2NYrx6XaWYmUUyq1x10uLHX6QGLS5rqcvttOU/rQLlCVLdoB/ATWJa+k9x71Y5ocfvp7uMMz8VMdPitOEojcFoF6EK+Few08ArYduN5O51LZmbDAFvIKEDUr3vBWdorSk+xwS3dXnDQvdu3tL0Kj+xum3rGyurl9QqWmtWaqdueKFO1C9okOcLjwGy6+72yIJ1QOVr6hcrEyMbhbytIIXmqaQHvdKbxvoNLqJsWlJ0If/QNqdVko/WFc/ll27m2Bevh8aas6MNjdrP0H7vatjvEB4Crt6/U+Fr2XOlwzF9FlJDIxIX6w4ouvRUKiwOXNpCkhOZj4AuMeoiYnWVBzV0J2AZh3ltb+E7bUnmlrPVDTveJA9QumlKslR8UxSrBMp9mSof8dywo6WgM+oDbgJkXBpZkKdy9V+ToHSRzWBdwgHmMv82axoKLsujQGD3Hdyb8SFzmP6/nls= ansible@ubuntu-c_

I've read that the issue could be regarding the .ssh/ permissions. When trying to change them in ubuntu-c and ubuntu1 hosts, the command didn't product any effect on the files:

_ansible@ubuntu-c:~/.ssh$ chmod 700 id_rsa
ansible@ubuntu-c:~/.ssh$ ll
total 13
drwxrwxrwx 1 ansible ansible 4096 Dec 21 09:39 ./
drwxrwxrwx 1 root    root    4096 Jan 12 10:58 ../
-rwxr-xr-x 1 ansible ansible 2602 Dec 21 09:37 id_rsa*
-rwxr-xr-x 1 ansible ansible  570 Dec 21 09:37 id_rsa.pub*
-rwxr-xr-x 1 ansible ansible  444 Dec 21 09:39 known_hosts*_

I tried to find a solution for the permissions issue but after reading in many places I'm stuck here.

Could you please help me?

Thanks a lot for your time.

**Comment by spurin** [comment]
Hi @SantiProven,

Would you mind please confirming for me the version of Windows so that I can track this accordingly?

I've found that older versions of Windows 10 which have the WSL v1, don't seem to mount directories as expected.  You can see in your output there, that the directory mounts are wide open as rwxrwxrwx -

```
drwxrwxrwx 1 ansible ansible 4096 Dec 21 09:39 ./
```

SSH will always reject keys from these directories as they are too open and unfortunately, even though I actually try to resolve this when the image starts up by setting the permissions correctly, it's not possible to change the permissions.

The workaround instead, is to the docker-compose.yaml file taken from here - https://github.com/spurin/diveintoansible-lab/blob/nonpersistent_home/docker-compose.yaml

Please replace this with your own.  With this file, it wont try to pass the ansible/root home directories as volume mounts and you'll have the correct permissions in place.  It has a slight disadvantage in that your data in the home directories wont persist (if you did a 'docker-compose rm' followed by a 'docker-compose up') but, as long as you know this you should be good.  

The /shared directory, will persist and as its not a home directory, you could use this instead, to checkout the code examples and make changes etc and if you did rebuild the environment, this would be kept :-)

Please let me know how you get on

**Comment by spurin** [comment]
@SantiProven further to my last email, there may be another way to address this that I haven't tried yet, but, I think it might work better...  If you're open to testing this with me I'd be happy to go through further details.

It is possible, to make SSHD less strict and this may just allow it to work as expected without changing the docker-compose.yaml file

As root on all of your hosts, if you were to change /etc/ssh/sshd_config and added the line -

```
StrictModes no
```

Then, restarted sshd with -

```
systemctl restart sshd
```

That may also fix the issue.  I will be testing this myself and if this is the case, I'll make this a default for the lab.

**Comment by SantiProven** [comment]
Hello @spurin 

I'm using Windows 10 Pro for Worktations.

I'll try StrictModes workarrownd and come back to you.

Thanks for your fast response.

Cheers

**Comment by SantiProven** [comment]
Hello @spurin 

not luck:

_systemctl restart sshd_

**Comment by spurin** [comment]
Hi @SantiProven,

I think on this you made progress but, are hindered by the permissions still not working on the client side.  Thanks for trying.

The best resolution at present without upgrading your windows host, will be to replace the docker-compose.yaml file with the one I provide from https://github.com/spurin/diveintoansible-lab/blob/nonpersistent_home/docker-compose.yaml

Could you give this a try.  Will work through any issues that arise.


Thanks


James Spurin

**Comment by spurin** [comment]
@SantiProven,

Would you share with me your .env file and the version of Windows, I'm going to see if I can recreate this issue.

The following thread, also looks like a good potential for resolution - 

https://devblogs.microsoft.com/commandline/chmod-chown-wsl-improvements/

Specifically, the metadata flag addition from a WSL environment -

```
sudo umount /mnt/c sudo mount -t drvfs C: /mnt/c -o metadata
```

It may also, be worth trying this if it matches your setup.

**Comment by SantiProven** [comment]
Hello @spurin 

I executed docker-compose rm.

Then I replaced the file docker-compose.yaml  you leaved here: https://github.com/spurin/diveintoansible-lab/blob/nonpersistent_home/docker-compose.yaml

After that I executed docker-compose up and generated keys again.

Now all it's working.

I'm bit busy now but I'll provide you all details that you are requested such the .env file.

Thank you so much!!!

Cheers

**Comment by SantiProven** [comment]
Hello,

here is my .env file:

# sshd ports
UBUNTUC_PORT_SSHD=2221
UBUNTU1_PORT_SSHD=2222
UBUNTU2_PORT_SSHD=2223
UBUNTU3_PORT_SSHD=2224
CENTOS1_PORT_SSHD=2225
CENTOS2_PORT_SSHD=2226
CENTOS3_PORT_SSHD=2227

# ttyd (web terminal) ports
UBUNTUC_PORT_TTYD=7681
UBUNTU1_PORT_TTYD=7682
UBUNTU2_PORT_TTYD=7683
UBUNTU3_PORT_TTYD=7684
CENTOS1_PORT_TTYD=7685
CENTOS2_PORT_TTYD=7686
CENTOS3_PORT_TTYD=7687

# Shared config volume
CONFIG=C:\Users\esdpos\diveintoansible-lab\config

# Shared home directories
ANSIBLE_HOME=C:\Users\esdpos\diveintoansible-lab\ansible_home

**Comment by SantiProven** [comment]
Here it's my .env file:

![image](https://user-images.githubusercontent.com/77323439/104335190-77492300-54f3-11eb-90fa-a7e85e9b964e.png)

**Comment by SantiProven** [comment]
Hello,

and here it's the OS version:

![image](https://user-images.githubusercontent.com/77323439/104335518-b9726480-54f3-11eb-9abc-e72d7abaac8f.png)


Cheers & thanks again

**Comment by SantiProven** [comment]
Hello @spurin 

Now looks like there is missing data in my repository:

ansible@ubuntu-c:~$ ls -la
total 40
drwxr-xr-x 4 ansible ansible 4096 Jan 13 08:35 .
drwxr-xr-x 1 root    root    4096 Jan 12 13:00 ..
-rw------- 1 ansible ansible   20 Jan 12 15:52 .bash_history
-rw-r--r-- 1 ansible ansible  220 Feb 25  2020 .bash_logout
-rw-r--r-- 1 ansible ansible 3771 Feb 25  2020 .bashrc
drwx------ 2 ansible ansible 4096 Jan 12 13:02 .cache
-rw-r--r-- 1 ansible ansible  807 Feb 25  2020 .profile
drwx------ 2 ansible ansible 4096 Jan 13 08:38 .ssh
-rw-r--r-- 1 ansible ansible    0 Jan 13 08:32 .sudo_as_admin_successful
-rw-r--r-- 1 ansible ansible  109 Aug 22 19:25 .vimrc
-rw-rw-r-- 1 ansible ansible    9 Jan 13 08:35 passowrd.txt

there is supposed to be there a "diveintoansible" folder with the repository content.

Is there any possibility that you can share it with me?

Cheers

**Comment by spurin** [comment]
Hi,

The diveintoansible folder should be checked out, it's covered in the 'Section 2 - Setting up the Course Repository' video.  In summary, it's running a git clone against the repo at https://github.com/spurin/diveintoansible

In your case, I recommend that rather than cloning in the ansible users home directory, you should be in /shared when you do the clone as this area is persistent whereas the ansible home, isnt (for the reasons we discussed above).

**Comment by SantiProven** [comment]
Hi,

Sorry for my stupid question. I skipped unconsciously this video.

Thank you again for the help

**Comment by spurin** [comment]
@SantiProven never a problem and easy to overlook these things.  Closing the issue.  Good luck with the rest of the course and please reach out if anything else is needed.
