### ISSUE TITLE
Ansible home directory is empty on ubuntu-c

### ISSUE THREAD

**Issue by amrani01** [spurin/diveintoansible-lab#91]
I did a git pull to get the latest images.  It looks like ubuntu-c image does not longer have the lab data.  I tried both the google cloud shell and downloading the lab on my Mac.  When I login to ubuntu-c, Ansible home directory is empty.  Could you please help.  Your course is amazing I go through it every time I need to refresh my knowledge with a topic.

**Comment by spurin** [comment]
Howdy @amrani01 

I think you're referring to the course repository.  It's not included in the lab by default and is instead a separate repo.  Maybe in some way you've missed that lesson.

Either way, it's super easy to resolve, if you do the following from the home directory you'll be good to go -

```
git clone https://github.com/spurin/diveintoansible.git
```

Best Regards


James Spurin

**Comment by spurin** [comment]
Oh and as well, thanks for your kind words!  Super Super appreciated! 😊

**Comment by amrani01** [comment]
Thank you so much for your quick response.  That resolved my issue.
