### ISSUE TITLE
SSH stuck at asking for password

### ISSUE THREAD

**Issue by dosilyoun** [spurin/diveintoansible-lab#93]
Checked out master branch

1. docker-compose up
2. ssh-keygen (all default)
3. ssh-copy-id ansible@ubuntu1 
4. ssh ubuntu1 -> still asks for password
after running the sshd as debug on ubuntu1 it said that /home/ansible/.ssh has incorrect access rights. It has 777 instead of 700.  Unfortunately chmod can't change these. Can you help me? 

More information: I am on windows :(

**Comment by domainfun** [comment]
> It has 777 instead of 700. Unfortunately chmod can't change these.

What `chmod` command did you run?  Was it `chmod 0700 /home/ansible/.ssh`?  I believe the leading zero is required.

**Comment by dosilyoun** [comment]
Hi @spurin!

The windows version is 21H1 build 19043.1586 and The docker version is 4.7.1 (77678). If there is any possibility to solve it on my PC, I go for it. Let's make the Google Cloud Shell as a B plan.

**Comment by spurin** [comment]
Your windows version looks good!  Did you have Docker already installed?  Could you try running the latest version of Docker Desktop

**Comment by dosilyoun** [comment]
@spurin This is the newest version.  What do you think?

`Docker Desktop 4.7.1 (77678) is currently the newest version available.
`

**Comment by dosilyoun** [comment]
@spurin Finally I changed the /home/ansible/.ssh to 700 and /home/ansible/.ssh/authorized_keys to 600
Then I run the sshd with debug on ubuntu1: `sudo /usr/sbin/sshd -d -p 22` (sudo is needed because without it, the sshd can't find host_keys).
The result is this:  ```
debug1: trying public key file /home/ansible/.ssh/authorized_keys
debug1: Could not open authorized keys '/home/ansible/.ssh/authorized_keys': Permission denied
```

**Comment by dosilyoun** [comment]
@spurin 

Finally I got the ssh working.

1. Modify the owners on hosts of .ssh and authorized keys to ansible
2. Then set 700  to .ssh folder and 600 to authorized_keys.

Do you have any idea how it can work out-of-box?

**Comment by spurin** [comment]
Hi @dosilyoun 

Great to hear you've got it working.  It should work, out of the box.  Was you running a prior version of either windows/Docker and then upgraded?

If so, the directory structure would have retained incorrect permissions.

You could test this if you like by stopping the environment, removing/renaming the ansible_home directory and then restarting (it will get recreated).

Let me know if you give this a try 👍

**Comment by Axell87** [comment]
Hi there!
I have the same problem. Try to reinstall ansible-lab for 3 times and delete all volumes. The sameresult.
Try to use different permissions.
@spurin, can you give more details about what exactly needs to be done for each of the hosts?

**Comment by spurin** [comment]
Hi @Axell87 

Sorry to hear you're having this issue, in the interim, the google cloud shell environment will be the best whilst we troubleshoot.

Can you please tell me what version of Docker Desktop you're using and if you're on windows, what version (start/run/winver).

Thanks

**Comment by Axell87** [comment]
One minute! its ok! I don't know how to use the google cloud shell, so i try to **use this in ubuntu1 host**
Modify the owners on hosts of .ssh and authorized keys to ansible
Then set 700 to .ssh folder and 600 to authorized_keys.
I do it with root, but nothing heppen as I guess. Rights have not changed.
my commands are:
```
root@ubuntu1:/home/ansible# chown -R ansible:ansible /home/ansible/.ssh/
root@ubuntu1:/home/ansible# chmod -R 700 /home/ansible/.ssh/
root@ubuntu1:/home/ansible# chmod -R 600 /home/ansible/.ssh/authorized_keys 
```

![bandicam 2022-08-16 16-00-47-864](https://user-images.githubusercontent.com/87781921/184886515-342e666c-a188-429e-8e08-8d1ed7d25468.jpg)

**Comment by spurin** [comment]
Hi @Axell87 

Unfortunately, the issue you're facing is a Docker/WSL issue where the permissions are not working as expected.

It's frustrating as it's one I can't fix as its system specific.

As the permissions are not being honoured, they are stuck as wide open - rwxrwxrwx ... ssh, doesn't like wide open permissions so it's blocking its use.

If you wanted to fix this, firstly try updating Docker Desktop the latest version, outside of that, it would be a Windows update which in turn, would update WSL.

Alternatively, you can launch the lab for free using Google Cloud Shell.  All you need is a google account and it's a one button click to launch.  See https://diveinto.com/p/playground

Then, follow the tutorial on the right hand side 👍

**Comment by Axell87** [comment]
Hello @spurin ! Thanks for you answers!
I update WSL with latest update files: wsl_update_x64 , enable WSL2, instead of WSL. Enable to use WSL2 in OS.
I usually do that.
I run WSL with ubuntu WSL terminal in Visual Studio Code.
Sorry for language.
![Безымянный](https://user-images.githubusercontent.com/87781921/184973030-ca563fcd-3bd8-487c-9f50-3d261e2a4155.jpg)

**Comment by spurin** [comment]
@Axell87 can you please share a screenshot of Docker Settings, Resources, WSL Integration

**Comment by Axell87** [comment]
@spurin  sure!!!
![bandicam 2022-08-16 23-39-17-750](https://user-images.githubusercontent.com/87781921/184981245-b4568ad3-3089-4e87-bd61-e6e42c525eae.jpg)
![bandicam 2022-08-16 23-39-34-377](https://user-images.githubusercontent.com/87781921/184981250-414e55a0-e9e5-4ef3-bb23-8676fb4b55b4.jpg)
![bandicam 2022-08-16 23-39-38-596](https://user-images.githubusercontent.com/87781921/184981251-55dbb44f-dcc0-40a2-b689-7095172d9514.jpg)
![bandicam 2022-08-16 23-41-10-317](https://user-images.githubusercontent.com/87781921/184981253-1ea9d595-692f-419a-a3c5-d9c32d2087ad.jpg)

**Comment by spurin** [comment]
Can you try toggling off Ubuntu WSL 2 support.  

In the diveintoansible-lab directory, rename ansible_home to something else (or remove it).

Then, using a standard command prompt, can you cd to the diveintoansible-lab directory and run -

docker-compose down -v
docker-compose up

When it's running see if the permissions are as expected

**Comment by Axell87** [comment]
Ok!! i'l try it tommorow and answer!! Thanks a lot!

**Comment by spurin** [comment]
Hi @Axell87 

This may actually be quite simple, where have you checked out the diveintoansible-lab?

If you haven't already, can you check it out to /Users/yourname (whatever your username is) and try it from there.

Thanks


James

**Comment by Axell87** [comment]
@spurin screenshots attached below
1. I enable Hyper-V (because of errors)
2.  /Users/yourname - can't find docker-compose file
So i go to **diveintoansible-lab-master** and do commands from here
4. Recreate all of machines from scratch
5. **I don't see new ansible_home directory**
6. **Now i cant get into ubuntu-c because of wrong login\password.**
very strange...

![bandicam 2022-08-17 11-13-41-386](https://user-images.githubusercontent.com/87781921/185077590-9ce45db3-8761-4bb6-8c43-44dbf5625189.jpg)
![bandicam 2022-08-17 11-36-51-452](https://user-images.githubusercontent.com/87781921/185077595-20fd4c73-5b39-479f-b0d6-767b427ac28a.jpg)
![bandicam 2022-08-17 11-50-35-340](https://user-images.githubusercontent.com/87781921/185077596-1068e759-7708-4df1-af92-ec56c6269286.jpg)
![bandicam 2022-08-17 11-51-44-190](https://user-images.githubusercontent.com/87781921/185077600-e2b64920-94ab-4758-8c95-815936ce94d0.jpg)
![bandicam 2022-08-17 11-53-47-464](https://user-images.githubusercontent.com/87781921/185077605-ddc6ef20-02b0-4315-923b-b0ee6221341d.jpg)
![bandicam 2022-08-17 11-53-52-944](https://user-images.githubusercontent.com/87781921/185077607-08b0ef54-b83a-465d-a779-784531a11e4d.jpg)

**Comment by spurin** [comment]
Hi @Axell87

Please re-enable the WSL2 option but leave everything else as it is, then

docker-compose rm
docker-compose up

It may be better to move this issue to Slack if you have that?  You could ping me there.  Here's an invite link http://community.diveinto.com

**Comment by Axell87** [comment]
to Slack if you have that?  - i don't have but i try to join.
2. Screens, i enable WSL2
3. I have a new catalog ansible_home directory but still can't log in


![bandicam 2022-08-17 13-03-37-970](https://user-images.githubusercontent.com/87781921/185096057-d2be9258-4d0a-4c65-9d28-69205f9c2c21.jpg)
![bandicam 2022-08-17 13-05-45-797](https://user-images.githubusercontent.com/87781921/185096063-cdef77ed-8a05-410b-bfa9-44e46cfb9339.jpg)

**Comment by spurin** [comment]
Hi @Axell87

Are you running the command prompt as an admin user?

The diveintoansible-lab folder needs to be in a standard user account and when running it from the command prompt, this needs to be using a standard command prompt as the same user.

**Comment by Axell87** [comment]
I am the only one user on machine and i am administrator.
I run PS in visual studio code, on screens before.
Should i run it from CMD (as administrator)??
or i can run it from WSL console?
![bandicam 2022-08-17 15-14-22-319](https://user-images.githubusercontent.com/87781921/185115939-515f48fe-ef4d-48fe-93e7-abaa27b63af3.jpg)

**Comment by Axell87** [comment]
W11 21H2 (22000.856) - the same result.

**Comment by spurin** [comment]
Hi @Axell87

If you're able to ping me via email, firstname@surname.com, I'll schedule a video session to troubleshoot this. I suspect it's WSL related still but going back and forth for this on GitHub will be tedious, let's fix and report back afterwards.

- James

**Comment by basireddym** [comment]
> 

I'm using wsl to set up the lab, but I'm facing the similar issue.
Unable to change owner, permission. even from the root user, I could not change them.

**Comment by spurin** [comment]
Hi @basireddym 

In the lab setup video I put a warning about using a WSL shell for setup but, I'm not too sure why this is being missed.

From what I've found, there's an issue with the WSL Docker integration and it breaks permissions.  Unfortunately it seems that once this is done, the bad permissions will remain until the lab is completely removed and started again, outside of WSL.

Could you please do the following -

1. Check that the lab is checked out to a location in C:\Users\YourUser
2. Using a command prompt, cd to the lab
3. Run docker-compose rm
4. Delete ansible_home if it exists
5. From the command prompt, run 
from a command prompt as your user docker-compose up
6. Check permissions

Please let me know how you get on.
