### ISSUE TITLE
Docker with Ansible-unable to connect to docker.

### ISSUE THREAD

**Issue by graham-hand1** [spurin/diveintoansible-lab#95]
Running through the docker with ansible section on a locally hosted lab setup using docker desktop on windows.  It seems the dind container is failing to start but when I try to get logs using the docker logs command there's no output.  Some other things I have tried:

- Was unable to ping docker so I added an entry into hosts for ubuntu-c for 172.18.0.8.
- Docker engine wasn't running so I started that.
- Was unable to execute any docker commands as the ansible user, added this user to the docker group
- curl -v 172.18.0.8:2375/info gives me a connection refused.

I'm thinking this is going to very likely be as a result of the dind container crashing.  I'd already done the things listed above before I took a look at docker desktop and saw dind (which I think I can safely assume is docker in docker) had exited (1).

Any assistance is greatly appreciated.

**Comment by spurin** [comment]
I'm working on course updates and will be completely re-writing this Docker section. I believe this issue was fixed shortly after with updates to the dind image. Closing for now.
