### ISSUE TITLE
Issue with Redshift/geoclue2

### ISSUE THREAD

**Issue by erickvd** [spurin/diveintoansible-lab#98]
Hello.

I'm trying to run your lab on my Linux Mint 20.3 and I have a problem when starting the lab with `docker compose up`.
Each time I run the command, an error occurs and my screens became ugly. I tried different things and it really seems that this error is related to the start of the labo.

I'm attaching a screenshot of the error to this post.
![docker-redshift-geoclue2-bug](https://user-images.githubusercontent.com/16934065/175896899-a02582ad-256c-402a-8186-a6ecb40ef149.png)
.

**Comment by erickvd** [comment]
I think it may be the same problem as #94

**Comment by spurin** [comment]
Hey @erickvd 

Thanks for the info on this and for the clarification.  I'm almost certain that this is the same issue.

Would you mind trying to run Docker Desktop Linux and seeing if this resolves?  It should as technically, Docker Desktop uses a hidden VM which should remove the failing interaction with your host machine.

Also, if you have cycles, we could try testing some custom images that with some further service removals to also see if this resolves.  I think that the base image, possibly has more services than that which are needed and this is impacting the host vm, when they run.

**Comment by erickvd** [comment]
I'll do a test with Docker Desktop for Linux and I'll give you some feedback.

**Comment by erickvd** [comment]
Hello

It will be longer than what I supposed. I had to enable kvm on my motherboard. Since then my computer is not booting anymore. 

I'm looking for a way to reset the factory settings.

**Comment by erickvd** [comment]
Hello.

I succeeded to recover. Docker Desktop is running for 3 days and I did not get the error. Its seems that the isolation is working.
