### ISSUE TITLE
Google cloud tutorial throws error after opening

### ISSUE THREAD

**Issue by coldje57** [spurin/diveintoansible-lab#99]
Followed this URL:  https://diveinto.com/p/playground  and the cloud shell created the images.  As I began to read the tutorial off to the right, the tutorial disappears and throws the error in the attached picture.

![tutorial](https://user-images.githubusercontent.com/56612048/176438600-edbcb949-a259-449c-b328-6a2fe41cfba4.jpg)

**Comment by spurin** [comment]
Thanks for letting me know about this.  I'm now seeing the same for my personal account.

It looks like Google Cloud Shell may have changed something.

For now, you can grab the tutorial details from https://github.com/spurin/diveintoansible-lab-gcp-cloudshell/blob/main/tutorial.md

I'll see if I can work out how this can be resolved.

**Comment by spurin** [comment]
@coldje57 - another workaround for now whilst this is going on.  If you launch the lab in Google Cloud Shell, it will error as per above, then, in the terminal type -

```
teachme tutorial.md
```

This will restore the tutorial to the right hand side and then, the error can be dismissed (might take a few clicks)
